Repository DSpace/DSpace, pull requests merged in 2018-08, with the labels that each got.

#2109 DS-3489: Search API query filter operator and facet prefix
  dspace-api/src/main/java/org/dspace/discovery/DiscoverQuery.java
  dspace-api/src/main/java/org/dspace/discovery/SearchService.java
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
  dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoverySearchFilter.java
  dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoverySearchFilterFacet.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/DiscoveryRestController.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/converter/DiscoverConfigurationConverter.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/converter/DiscoverFacetConfigurationConverter.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/converter/DiscoverFacetResultsConverter.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/converter/DiscoverFacetsConverter.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/converter/DiscoverResultConverter.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/converter/query/SearchQueryConverter.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/link/HalLinkService.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/link/search/DiscoveryRestHalLinkFactory.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/link/search/FacetConfigurationResourceHalLinkFactory.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/link/search/FacetsResourceHalLinkFactory.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/link/search/SearchConfigurationResourceHalLinkFactory.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/link/search/SearchFacetEntryHalLinkFactory.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/link/search/SearchResultsResourceHalLinkFactory.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/link/search/SearchSupportHalLinkFactory.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/FacetResultsRest.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/SearchConfigurationRest.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/SearchFacetEntryRest.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/hateoas/DSpaceResource.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/hateoas/EmbeddedPage.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/hateoas/FacetsResource.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/hateoas/HALResource.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/hateoas/SearchResultsResource.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/query/RestSearchOperator.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/DiscoveryRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/utils/DiscoverQueryBuilder.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/converter/query/SearchQueryConverterTest.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/CommunityMatcher.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/FacetEntryMatcher.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/SearchFilterMatcher.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/SortOptionMatcher.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/test/AbstractControllerIntegrationTest.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/utils/DiscoverQueryBuilderTest.java
  dspace/config/spring/api/discovery.xml
  dspace/solr/search/conf/schema.xml
Labels: REST API v7

#2145 DS-3498 quick fix. Disable full text snippets in search results & add warning (for master)
  dspace/config/spring/api/discovery.xml
Labels: bug

#2146 DS-3522: Ensure Submission Policies are removed in XMLWorkflow (for master)
  dspace-api/src/main/java/org/dspace/xmlworkflow/XmlWorkflowServiceImpl.java
Labels: bug

#2147 DS-3616] Fix nested vocabulary search (master)
  dspace-api/src/main/java/org/dspace/content/authority/DSpaceControlledVocabulary.java
Labels: bug, quick win

#2148 DS-3681: Refactoring of DSpaceAuthorityIndexer (for master)
  dspace-api/src/main/java/org/dspace/authority/AuthorityServiceImpl.java
  dspace-api/src/main/java/org/dspace/authority/AuthoritySolrServiceImpl.java
  dspace-api/src/main/java/org/dspace/authority/indexer/AuthorityIndexClient.java
  dspace-api/src/main/java/org/dspace/authority/indexer/AuthorityIndexerInterface.java
  dspace-api/src/main/java/org/dspace/authority/indexer/AuthorityIndexingService.java
  dspace-api/src/main/java/org/dspace/authority/indexer/DSpaceAuthorityIndexer.java
Labels: bug, code task

#2054 DS-3447: ORCID v2 integration (port to master from PR#2039)
  dspace-api/pom.xml
  dspace-api/src/main/java/org/dspace/authority/SolrAuthorityInterface.java
  dspace-api/src/main/java/org/dspace/authority/orcid/Orcid.java
  dspace-api/src/main/java/org/dspace/authority/orcid/OrcidAuthorityValue.java
  dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv2.java
  dspace-api/src/main/java/org/dspace/authority/orcid/Orcidv2AuthorityValue.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/Bio.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/BioExternalIdentifier.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/BioName.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/BioResearcherUrl.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/Citation.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/CitationType.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/Contributor.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/ContributorAttribute.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/ContributorAttributeRole.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/ContributorAttributeSequence.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/Work.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/WorkExternalIdentifier.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/WorkExternalIdentifierType.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/WorkTitle.java
  dspace-api/src/main/java/org/dspace/authority/orcid/model/WorkType.java
  dspace-api/src/main/java/org/dspace/authority/orcid/xml/Converter.java
  dspace-api/src/main/java/org/dspace/authority/orcid/xml/XMLErrors.java
  dspace-api/src/main/java/org/dspace/authority/orcid/xml/XMLtoBio.java
  dspace-api/src/main/java/org/dspace/authority/orcid/xml/XMLtoWork.java
  dspace-api/src/main/java/org/dspace/authority/rest/RESTConnector.java
  dspace-api/src/main/java/org/dspace/authority/rest/RestSource.java
  dspace-api/src/main/java/org/dspace/content/authority/SolrAuthority.java
  dspace-spring-rest/pom.xml
  dspace/config/dspace.cfg
  dspace/config/spring/api/orcid-authority-services.xml
  pom.xml
Labels: bug, high priority

#2149 DS-3702 & DS-3703: Rebuild the old behavior of bitstreams during vers… (for master)
  dspace-api/src/main/java/org/dspace/content/BitstreamServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/service/BitstreamService.java
  dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java
  dspace-api/src/main/java/org/dspace/storage/bitstore/service/BitstreamStorageService.java
  dspace-api/src/main/java/org/dspace/versioning/AbstractVersionProvider.java
Labels: bug

#2150 DS-3769 Set the right hibernate property of … (for master)
  dspace-api/src/main/java/org/dspace/eperson/dao/impl/SubscriptionDAOImpl.java
Labels: bug, quick win

#2152 DS-3707, DS-3715: Fixes to item level embargo/privacy in OAI-PMH (for master)
  dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/service/ItemService.java
  dspace-api/src/test/java/org/dspace/content/ItemTest.java
  dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java
  dspace/solr/oai/conf/schema.xml
Labels: bug

#2153 DS-3856 - foreignkey-constraint community2community_child_comm_id_fkey (for master)
  dspace-api/src/main/java/org/dspace/content/CommunityServiceImpl.java
  dspace-api/src/test/java/org/dspace/content/ITCommunityCollection.java
Labels: bug

#2154 [DS-3310] Fix authentication problem in SwordV2 implementation (for master)
  dspace-api/src/main/java/org/dspace/content/Item.java
  dspace-swordv2/src/main/java/org/dspace/sword2/SwordAuthenticator.java
Labels: bug, quick win

#2155 DS-3768 Fixes the harvest solr parse error by (for master)
  dspace-api/src/main/java/org/dspace/search/Harvest.java
Labels: bug, quick win

#2144 [DS-3377] Solr queries too long (change search GET requests to POST) (for master)
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
Labels: bug, improvement

#2059 [DS-3693] Port pull request #1838 to master
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceFileInfoPlugin.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/SearchFilterMatcher.java
  dspace/config/spring/api/discovery.xml
Labels: feature, quick win

#2157 Ds 3629 listing of all groups misses pagination - XMLUI (for master)
  dspace-api/src/main/java/org/dspace/eperson/GroupServiceImpl.java
Labels: bug, quick win

#2156 DS-3700: MediaFilterServiceImpl forgot to close an input stream (for master)
  dspace-api/src/main/java/org/dspace/app/mediafilter/MediaFilterServiceImpl.java
  dspace-api/src/main/java/org/dspace/storage/bitstore/DSBitStoreService.java
Labels: bug, high priority

#2159 DS-3933 Updated Pubmed endpoints from http:// to https:// (for master)
  dspace-api/src/main/java/org/dspace/importer/external/pubmed/service/PubmedImportMetadataSourceServiceImpl.java
  dspace-api/src/main/java/org/dspace/submit/lookup/PubmedService.java
  dspace-api/src/main/resources/spring/spring-dspace-addon-import-services.xml
  dspace/config/modules/publication-lookup.cfg
Labels: bug

#2134 [DS-3967] 6x - Migrate Dockerfile to DSpace/DSpace
  .dockerignore
  Dockerfile
  dspace/src/main/docker/local.cfg
Labels: improvement

#2108 DS-3910 Delete method on item endpoint
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/ItemRestRepository.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/builder/AbstractBuilder.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/builder/CollectionBuilder.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/builder/WorkspaceItemBuilder.java
Labels: REST API v7

#2163 DS-3489: search rest endpoint angular alignment rebased on master
  dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoverySearchFilter.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/converter/DiscoverFacetsConverter.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/SearchConfigurationRest.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/SearchFacetEntryRest.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/FacetEntryMatcher.java
  dspace/config/spring/api/discovery.xml
Labels: REST API v7

#2135 [DS-3967] 7x - Migrate Dockerfile to DSpace/DSpace
  .dockerignore
  Dockerfile
  dspace/src/main/docker/local.cfg
Labels: REST API v7

#2126 DS-3735 DS-3924 DS-3737 Implement CREATE, DELETE and some search methods for the EPersons endpoint
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/EPersonRest.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/EPersonRestRepository.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/EPersonRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/builder/AbstractDSpaceObjectBuilder.java
Labels: REST API v7

#2072 Fix typo "verion"
  dspace-api/src/main/java/org/dspace/identifier/IdentifierServiceImpl.java
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/versioning/VersionHistoryForm.java
Labels: XMLUI, code task, port to master, quick win

#2071 DS-3919: Rename identifier-service-test.xml to identifier-service.xml
  dspace-api/src/test/data/dspaceFolder/config/spring/api/identifier-service.xml
Labels: bug, configuration, port to master, quick win

#2010 DS-3885. Minor fix on CommunityServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/CommunityServiceImpl.java
Labels: bug, port to 6.x, quick win

#2104 [DS-3938] Use JDK7-compatible PostgreSQL JDBC driver in DSpace 5.x
  pom.xml
Labels: bug, database: Postgres, quick win

#1976 DS-3542 Spring security authorizations 2
  dspace-api/src/main/java/org/dspace/eperson/dao/impl/EPersonDAOImpl.java
  dspace-spring-rest/pom.xml
  dspace-spring-rest/src/main/java/org/dspace/app/rest/BitstreamContentRestController.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/link/DSpaceResourceHalLinkFactory.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/hateoas/DSpaceRelProvider.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/model/hateoas/DSpaceResource.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/AuthorityEntryLinkRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/AuthorityEntryValueLinkRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/AuthorityRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/BitstreamRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/CollectionRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/CommunityRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/DSpaceRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/EPersonRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/GroupRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/ItemRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/LicenseRestLinkRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/ResourcePolicyRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/SubmissionDefinitionRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/SubmissionFormRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/SubmissionPanelRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/SubmissionUploadRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/WorkspaceItemRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/AdminRestPermissionEvaluatorPlugin.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/AuthorizeServicePermissionEvaluatorPlugin.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/DSpace401AuthenticationEntryPoint.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/DSpaceObjectPermissionEvaluatorPlugin.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/DSpacePermissionEvaluator.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/DSpaceRestPermission.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/EPersonRestAuthenticationProvider.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/EPersonRestPermissionEvaluatorPlugin.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/GroupRestPermissionEvaluatorPlugin.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/MethodSecurityConfig.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/RestAuthenticationService.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/RestPermissionEvaluatorPlugin.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/StatelessLoginFilter.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/security/jwt/JWTTokenRestAuthenticationServiceImpl.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/utils/RestRepositoryUtils.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/BitstreamRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/BrowsesResourceControllerIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/EPersonRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/EmptyRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/GroupRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/SubmissionDefinitionsControllerIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/SubmissionFormsControllerIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/SubmissionSectionsControllerIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/SubmissionUploadsControllerIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/builder/EPersonBuilder.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/builder/ItemBuilder.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/EPersonMatcher.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/EPersonMetadataMatcher.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/ItemMatcher.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/security/EPersonRestAuthenticationProviderTest.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/test/AbstractControllerIntegrationTest.java
Labels: REST API v7
