Repository DSpace/DSpace, pull requests merged in 2018-07, with the labels that each got.

#2107 DS-3939 OAI-Harvester, skip item and continue if handle is missing
  dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java
Labels: bug, quick win

#2106 DS-3939 OAI-Harvester, skip item and continue if handle is missing
  dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java
Labels: bug, quick win

#2064 DS-3909: Adding withdraw, reinstate, and isDiscoverable support to item repository.
  dspace-spring-rest/src/main/java/org/dspace/app/rest/RestResourceController.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/ItemRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/AbstractResourcePatch.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/ItemPatch.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/builder/CollectionBuilder.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/builder/ItemBuilder.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/test/AbstractControllerIntegrationTest.java
Labels: REST API v7

#1931 DS-3782 upgrade commons collections to version 4
  dspace-api/pom.xml
  dspace-api/src/main/java/org/dspace/administer/CommunityFiliator.java
  dspace-api/src/main/java/org/dspace/app/itemimport/ItemImportServiceImpl.java
  dspace-api/src/main/java/org/dspace/app/util/Util.java
  dspace-api/src/main/java/org/dspace/authenticate/IPAuthentication.java
  dspace-api/src/main/java/org/dspace/authenticate/LDAPAuthentication.java
  dspace-api/src/main/java/org/dspace/authenticate/PasswordAuthentication.java
  dspace-api/src/main/java/org/dspace/authenticate/ShibAuthentication.java
  dspace-api/src/main/java/org/dspace/authenticate/X509Authentication.java
  dspace-api/src/main/java/org/dspace/authority/indexer/DSpaceAuthorityIndexer.java
  dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java
  dspace-api/src/main/java/org/dspace/authorize/ResourcePolicyServiceImpl.java
  dspace-api/src/main/java/org/dspace/checker/CheckerCommand.java
  dspace-api/src/main/java/org/dspace/content/BitstreamFormatServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/BitstreamServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/BundleServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/CommunityServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/DSpaceObject.java
  dspace-api/src/main/java/org/dspace/content/DSpaceObjectServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/MetadataFieldServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/crosswalk/AIPTechMDCrosswalk.java
  dspace-api/src/main/java/org/dspace/content/dao/impl/CommunityDAOImpl.java
  dspace-api/src/main/java/org/dspace/content/packager/AbstractMETSIngester.java
  dspace-api/src/main/java/org/dspace/content/packager/DSpaceAIPDisseminator.java
  dspace-api/src/main/java/org/dspace/content/packager/PackageUtils.java
  dspace-api/src/main/java/org/dspace/core/AbstractHibernateDAO.java
  dspace-api/src/main/java/org/dspace/core/AbstractHibernateDSODAO.java
  dspace-api/src/main/java/org/dspace/discovery/FullTextContentStreams.java
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
  dspace-api/src/main/java/org/dspace/eperson/EPersonServiceImpl.java
  dspace-api/src/main/java/org/dspace/eperson/GroupServiceImpl.java
  dspace-api/src/main/java/org/dspace/eperson/RegistrationDataServiceImpl.java
  dspace-api/src/main/java/org/dspace/eperson/dao/impl/EPersonDAOImpl.java
  dspace-api/src/main/java/org/dspace/handle/HandleServiceImpl.java
  dspace-api/src/main/java/org/dspace/importer/external/datamodel/Query.java
  dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java
  dspace-api/src/main/java/org/dspace/versioning/VersionHistoryServiceImpl.java
  dspace-api/src/main/java/org/dspace/workflowbasic/BasicWorkflowServiceImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/XmlWorkflowServiceImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/ClaimedTaskServiceImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/InProgressUserServiceImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/PoolTaskServiceImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/WorkflowItemRoleServiceImpl.java
  dspace-api/src/test/java/org/dspace/content/BitstreamFormatTest.java
  dspace-api/src/test/java/org/dspace/content/BundleTest.java
  dspace-services/pom.xml
  pom.xml
Labels: REST API v7, code task, quick win

#2042 [DS-3895] Bitstream size can't be referenced in HQL queries
  dspace-api/src/main/java/org/dspace/app/itemexport/ItemExportServiceImpl.java
  dspace-api/src/main/java/org/dspace/app/mediafilter/MediaFilterServiceImpl.java
  dspace-api/src/main/java/org/dspace/app/util/GoogleBitstreamComparator.java
  dspace-api/src/main/java/org/dspace/app/util/SyndicationFeed.java
  dspace-api/src/main/java/org/dspace/checker/ResultsLogger.java
  dspace-api/src/main/java/org/dspace/checker/SimpleReporterServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/Bitstream.java
  dspace-api/src/main/java/org/dspace/content/BitstreamServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/InstallItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/crosswalk/OREDisseminationCrosswalk.java
  dspace-api/src/main/java/org/dspace/content/crosswalk/PREMISCrosswalk.java
  dspace-api/src/main/java/org/dspace/content/packager/AbstractMETSDisseminator.java
  dspace-api/src/main/java/org/dspace/ctask/general/BitstreamsIntoMetadata.java
  dspace-api/src/main/java/org/dspace/discovery/FullTextContentStreams.java
  dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java
  dspace-api/src/test/java/org/dspace/app/util/GoogleBitstreamComparatorTest.java
  dspace-api/src/test/java/org/dspace/content/BitstreamTest.java
  dspace-api/src/test/java/org/dspace/content/InstallItemTest.java
  dspace-api/src/test/java/org/dspace/discovery/FullTextContentStreamsTest.java
  dspace-jspui/src/main/java/org/dspace/app/webui/jsptag/ItemTag.java
  dspace-jspui/src/main/java/org/dspace/app/webui/servlet/BitstreamServlet.java
  dspace-jspui/src/main/java/org/dspace/app/webui/servlet/HTMLServlet.java
  dspace-jspui/src/main/java/org/dspace/app/webui/servlet/RetrieveServlet.java
  dspace-jspui/src/main/java/org/dspace/app/webui/submit/step/JSPUploadStep.java
  dspace-jspui/src/main/java/org/dspace/app/webui/submit/step/JSPUploadWithEmbargoStep.java
  dspace-jspui/src/main/webapp/submit/change-file-description.jsp
  dspace-jspui/src/main/webapp/submit/get-file-format.jsp
  dspace-jspui/src/main/webapp/submit/show-uploaded-file.jsp
  dspace-jspui/src/main/webapp/submit/upload-file-list.jsp
  dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java
  dspace-rest/src/main/java/org/dspace/rest/common/Bitstream.java
  dspace-rest/src/main/java/org/dspace/rest/filter/ItemFilterUtil.java
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/UploadStep.java
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/submission/submit/UploadWithEmbargoStep.java
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/cocoon/BitstreamReader.java
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/objectmanager/AbstractAdapter.java
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/objectmanager/ItemAdapter.java
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/utils/DSpaceValidity.java
Labels: bug

#2031 [DS-3895] Bitstream size can't be referenced in HQL queries
  dspace-api/src/main/java/org/dspace/app/itemexport/ItemExportServiceImpl.java
  dspace-api/src/main/java/org/dspace/app/mediafilter/MediaFilterServiceImpl.java
  dspace-api/src/main/java/org/dspace/app/util/GoogleBitstreamComparator.java
  dspace-api/src/main/java/org/dspace/app/util/SyndicationFeed.java
  dspace-api/src/main/java/org/dspace/checker/ResultsLogger.java
  dspace-api/src/main/java/org/dspace/checker/SimpleReporterServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/Bitstream.java
  dspace-api/src/main/java/org/dspace/content/InstallItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/crosswalk/OREDisseminationCrosswalk.java
  dspace-api/src/main/java/org/dspace/content/crosswalk/PREMISCrosswalk.java
  dspace-api/src/main/java/org/dspace/content/packager/AbstractMETSDisseminator.java
  dspace-api/src/main/java/org/dspace/ctask/general/BitstreamsIntoMetadata.java
  dspace-api/src/main/java/org/dspace/discovery/FullTextContentStreams.java
  dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java
  dspace-api/src/test/java/org/dspace/app/util/GoogleBitstreamComparatorTest.java
  dspace-api/src/test/java/org/dspace/content/BitstreamTest.java
  dspace-api/src/test/java/org/dspace/content/InstallItemTest.java
  dspace-api/src/test/java/org/dspace/discovery/FullTextContentStreamsTest.java
  dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java
  dspace-rest/src/main/java/org/dspace/rest/common/Bitstream.java
  dspace-rest/src/main/java/org/dspace/rest/filter/ItemFilterUtil.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/BitstreamContentRestController.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/converter/BitstreamConverter.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/submit/SubmissionService.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/BitstreamMatcher.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/matcher/CollectionMatcher.java
Labels: bug
