Repository DSpace/DSpace, pull requests merged in 2019-06, with the labels that each got.

#2116 [DS-3953] Externalize hard-coded list of metadata registry files in updater
  dspace-api/src/main/java/org/dspace/storage/rdbms/DatabaseRegistryUpdater.java
  dspace/config/dspace.cfg
Labels: backend: configuration, improvement, quick win

#2437 [DS-4259] HAL login form does not support special characters
  dspace-spring-rest/src/main/webapp/login.html
Labels: REST API v7, bug, quick win

#2224 [DS-4032] RequestItem.isAccept_request() can NPE if setAccept_request() was never called.
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItem.java
Labels: bug, port to 6.x, quick win

#2444 DS-4269 Incorrect hal pagination links in the browses endpoint
  dspace-spring-rest/src/main/java/org/dspace/app/rest/RestResourceController.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/link/BrowseEntryHalLinkFactory.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/BrowsesResourceControllerIT.java
Labels: REST API v7, quick win

#2403 [DS-4217] applied the name refactor and rewrote BadRequestException t…
  dspace-spring-rest/src/main/java/org/dspace/app/rest/RestResourceController.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/exception/DSpaceBadRequestException.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/exception/InvalidDSpaceObjectTypeException.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/exception/InvalidRequestException.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/exception/InvalidSearchFacetException.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/exception/InvalidSearchFilterException.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/exception/InvalidSortingException.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/CollectionRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/CommunityRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/DSpaceRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/DiscoveryRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/ItemRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/MetadataFieldRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/MetadataSchemaRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/WorkflowItemRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/WorkspaceItemRestRepository.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/AbstractResourcePatch.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/EPersonPatch.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/ItemPatch.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/EPersonOperationFactory.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/ItemOperationFactory.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/impl/EPersonCertificateReplaceOperation.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/impl/EPersonEmailReplaceOperation.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/impl/EPersonLoginReplaceOperation.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/impl/EPersonNetidReplaceOperation.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/impl/ItemDiscoverableReplaceOperation.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/impl/ItemWithdrawReplaceOperation.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/impl/PatchOperation.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/impl/ReplacePatchOperation.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/patch/factories/impl/ResourcePatchOperation.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/utils/DiscoverQueryBuilder.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/CollectionRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/utils/DiscoverQueryBuilderTest.java
Labels: REST API v7, bug

#2440 DS-4230 - PUT contract in relationships
  dspace-spring-rest/src/main/java/org/dspace/app/rest/RelationshipRestController.java
  dspace-spring-rest/src/main/java/org/dspace/app/rest/repository/RelationshipRestRepository.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/RelationshipRestRepositoryIT.java
Labels: REST API v7, component: configurable entities

#2432 DS-4252 Discovery re-index doesn't work without -b
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
Labels: REST API v7, quick win

#2452 [DS-4032] RequestItem.isAccept_request() can NPE if setAccept_request() was never called.
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItem.java
Labels: bug, quick win

#2425 Minor dependency updates for `master` (pre-7.0)
  dspace-api/pom.xml
  dspace-api/src/main/java/org/dspace/app/mediafilter/PDFBoxThumbnail.java
  dspace-api/src/main/java/org/dspace/app/mediafilter/PDFFilter.java
  pom.xml
Labels: high priority, quick win

#2458 DS-2376: Catch exception from encrypted PDF instead of expecting to test for it. (Bug fix follow-up)
  dspace-api/src/main/java/org/dspace/app/mediafilter/PDFBoxThumbnail.java
  dspace-api/src/main/java/org/dspace/app/mediafilter/PDFFilter.java
Labels: bug

#2448 Some minor code cleanup in the tests
  dspace-api/src/main/java/org/dspace/discovery/FullTextContentStreams.java
  dspace-api/src/main/java/org/dspace/eperson/dao/impl/GroupDAOImpl.java
  dspace-api/src/test/java/org/dspace/app/util/GoogleBitstreamComparatorTest.java
  dspace-api/src/test/java/org/dspace/app/util/GoogleMetadataTest.java
  dspace-api/src/test/java/org/dspace/app/util/IndexVersionTest.java
  dspace-api/src/test/java/org/dspace/checker/dao/impl/ChecksumHistoryDAOImplTest.java
  dspace-api/src/test/java/org/dspace/content/BundleTest.java
  dspace-api/src/test/java/org/dspace/content/CommunityTest.java
  dspace-api/src/test/java/org/dspace/content/LicenseUtilsTest.java
  dspace-api/src/test/java/org/dspace/content/packager/ITDSpaceAIP.java
  dspace-api/src/test/java/org/dspace/core/ContextTest.java
  dspace-api/src/test/java/org/dspace/curate/ITCurator.java
  dspace-api/src/test/java/org/dspace/discovery/FullTextContentStreamsTest.java
  dspace-api/src/test/java/org/dspace/eperson/GroupTest.java
  dspace-api/src/test/java/org/dspace/statistics/util/TestLocationUtils.java
  dspace-spring-rest/src/test/java/org/dspace/app/rest/test/AbstractControllerIntegrationTest.java
Labels: code task, quick win
