Repository DSpace/DSpace, pull requests merged in 2020-11, with the labels that each got.

#3015 More fixes based on LGTM.com feedback
  dspace-api/src/main/java/org/dspace/app/itemimport/ItemImportServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/RelationshipMetadataValue.java
  dspace-api/src/main/java/org/dspace/content/packager/METSManifest.java
  dspace-api/src/main/java/org/dspace/ctask/general/MetadataWebService.java
  dspace-api/src/main/java/org/dspace/harvest/HarvestScheduler.java
  dspace-api/src/main/java/org/dspace/identifier/doi/DOIOrganiser.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/DatabaseUtils.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/AuthenticationRestController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessLoginFilter.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthenticationRestControllerIT.java
  dspace-sword/src/main/java/org/purl/sword/base/SWORDEntry.java
Labels: 1 APPROVAL, bug, code task

#3031 Bugfix IRUS Integration with Entities
  dspace-api/src/main/java/org/dspace/statistics/export/processor/ExportEventProcessor.java
  dspace-api/src/test/java/org/dspace/statistics/export/processor/ExportEventProcessorTest.java
Labels: 1 APPROVAL, bug, component: configurable entities

#3030 Uri parameters not added for self link
  dspace-server-webapp/src/main/java/org/dspace/app/rest/RestResourceController.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RestResourceControllerIT.java
Labels: 1 APPROVAL, REST API v7, hacktoberfest-accepted

#3042 IRUS property in build.xml when updating spiders
  dspace/src/main/config/build.xml
Labels: 1 APPROVAL, bug

#3026 Submission from external source rejected with 403
  dspace-api/src/main/java/org/dspace/external/service/impl/ExternalDataServiceImpl.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/WorkspaceItemRestRepositoryIT.java
Labels: 1 APPROVAL, bug, component: submission, tools: external-sources

#3038 Importing new csv with relationships
  dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataImport.java
  dspace-api/src/test/java/org/dspace/app/bulkedit/MetadataImportIT.java
  dspace-api/src/test/java/org/dspace/app/bulkedit/MetadataImportTest.java
Labels: 1 APPROVAL, bug, component: configurable entities, tools: batch-editing

#3037 Supporting CSV import removing values
  dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataImport.java
  dspace-api/src/test/java/org/dspace/app/bulkedit/MetadataImportIT.java
Labels: 1 APPROVAL, bug, tools: batch-editing

#3039 CSV Import error with Virtual Metadata fix
  dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataImport.java
  dspace-api/src/test/java/org/dspace/app/csv/CSVMetadataImportReferenceIT.java
Labels: 1 APPROVAL, bug, component: configurable entities, tools: batch-editing

#3036 support CSV import to schema "person"
  dspace-api/src/main/java/org/dspace/app/bulkedit/DSpaceCSV.java
  dspace-api/src/test/java/org/dspace/app/bulkedit/MetadataImportIT.java
Labels: 1 APPROVAL, bug, merge conflict, tools: batch-editing

#3051 Added self link to root endpoint
  dspace-server-webapp/src/main/java/org/dspace/app/rest/link/RootHalLinkFactory.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RootRestResourceControllerIT.java
Labels: 1 APPROVAL

#3050 Fix pagination issue in a couple of search endpoints
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/CollectionRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/EPersonRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/GroupRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ResourcePolicyRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/CollectionRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/EPersonRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/GroupRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ResourcePolicyRestRepositoryIT.java
Labels: 1 APPROVAL, REST API v7, bug

#3041 Issue 2988: EPerson Password Replacement/addition with ADD Patch Operation instead of REPLACE
  dspace-api/src/test/java/org/dspace/builder/EPersonBuilder.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/patch/operation/EPersonPasswordAddOperation.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/patch/operation/PatchOperation.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/EPersonRestPermissionEvaluatorPlugin.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/EPersonRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/security/EPersonRestPermissionEvaluatorPluginTest.java
Labels: 1 APPROVAL, authentication: EPerson, bug

#3009 Refactor/remove custom MultipartFileSender to use Spring Boot Range requests
  dspace-server-webapp/src/main/java/org/dspace/app/rest/BitstreamRestController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/SitemapRestController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/BitstreamResource.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/HttpHeadersInitializer.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/MultipartFileSender.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/BitstreamRestControllerIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/utils/MultipartFileSenderTest.java
Labels: REST API v7, hacktoberfest-accepted

#3046 Metadata identifier for Communities and Collections
  dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/CommunityServiceImpl.java
  dspace-api/src/main/java/org/dspace/identifier/DOIIdentifierProvider.java
  dspace-api/src/main/java/org/dspace/identifier/EZIDIdentifierProvider.java
  dspace-api/src/main/java/org/dspace/identifier/HandleIdentifierProvider.java
  dspace-api/src/main/java/org/dspace/identifier/IdentifierServiceImpl.java
  dspace-api/src/main/java/org/dspace/identifier/VersionedHandleIdentifierProvider.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/V7_0_2020_10_31__CollectionCommunity_Metadata_Handle.java
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/metadata/h2/V7.0_2020.10.31__CollectionCommunity_Metadata_Handle.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/metadata/oracle/V7.0_2020.10.31__CollectionCommunity_Metadata_Handle.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/metadata/postgres/V7.0_2020.10.31__CollectionCommunity_Metadata_Handle.sql
  dspace-api/src/test/java/org/dspace/content/CollectionTest.java
  dspace-api/src/test/java/org/dspace/content/CommunityTest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/MetadataConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/CollectionRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/CommunityRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/CollectionRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/EPersonRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/MetadataMatcher.java
Labels: 1 APPROVAL, backend: FlywayDB, bug

#3029 Cleanup unused POM dependencies & minor security updates
  dspace-api/pom.xml
  dspace-oai/pom.xml
  dspace-swordv2/pom.xml
  dspace/modules/server/pom.xml
  pom.xml
Labels: 1 APPROVAL, code task, dependencies

#3018 Upgrade OAI-PMH to Bootstrap 4 (via WebJars)
  dspace-oai/src/main/resources/static/css/bootstrap-theme.css
  dspace-oai/src/main/resources/static/css/bootstrap-theme.min.css
  dspace-oai/src/main/resources/static/css/bootstrap.css
  dspace-oai/src/main/resources/static/css/bootstrap.min.css
  dspace-oai/src/main/resources/static/fonts/glyphicons-halflings-regular.eot
  dspace-oai/src/main/resources/static/fonts/glyphicons-halflings-regular.svg
  dspace-oai/src/main/resources/static/fonts/glyphicons-halflings-regular.ttf
  dspace-oai/src/main/resources/static/fonts/glyphicons-halflings-regular.woff
  dspace-oai/src/main/resources/static/img/dspace-logo.png
  dspace-oai/src/main/resources/static/img/lyncode.png
  dspace-oai/src/main/resources/static/js/bootstrap.js
  dspace-oai/src/main/resources/static/js/bootstrap.min.js
  dspace-oai/src/main/resources/static/js/jquery.js
  dspace-oai/src/main/resources/static/lyncode.png
  dspace-oai/src/main/resources/static/style.xsl
  dspace-oai/src/main/resources/templates/index.twig.html
  dspace-server-webapp/pom.xml
Labels: 1 APPROVAL, bug, interface: OAI-PMH

#3048 Disable stacktrace in error responses by default. Document how to enable for development
  dspace-server-webapp/src/main/resources/application.properties
Labels: 1 APPROVAL, bug, code task

#3060 Add CI to GitHub via Actions (based on Travis CI config)
  .codecov.yml
  .github/workflows/build.yml
  .travis.yml
Labels: 1 APPROVAL, code task, high priority

#3064 Add CI to GitHub via Actions (based on Travis CI config) for 6.x
  .github/workflows/build.yml
  .travis.yml
Labels: 1 APPROVAL, code task, high priority

#3065 Add CI to GitHub via Actions (based on Travis CI config) for 5.x
  .github/workflows/build.yml
  .travis.yml
Labels: 1 APPROVAL, code task, high priority

#3072 Update build.yml to not limit by branch
  .github/workflows/build.yml
Labels: 1 APPROVAL, code task, port to 6.x

#2780 Upgrade to the ORCID v3 API
  dspace-api/pom.xml
  dspace-api/src/main/java/org/dspace/external/OrcidRestConnector.java
  dspace-api/src/main/java/org/dspace/external/provider/impl/OrcidV3AuthorDataProvider.java
  dspace-api/src/main/java/org/dspace/external/provider/orcid/xml/XMLtoBio.java
  dspace-api/src/test/data/dspaceFolder/config/spring/api/external-services.xml
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ExternalSourcesRestControllerIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/OrcidExternalSourcesIT.java
  dspace-server-webapp/src/test/resources/org/dspace/app/rest/orcid-person-record.xml
  dspace-server-webapp/src/test/resources/org/dspace/app/rest/orcid-search.xml
  dspace/config/dspace.cfg
  dspace/config/spring/api/external-services.xml
Labels: REST API v7
