Repository DSpace/DSpace, pull requests merged in 2020-12, with the labels that each got.

#3002 Support itemService.getMetadata with virtual md field
  dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/virtual/Related.java
  dspace-api/src/test/java/org/dspace/builder/ItemBuilder.java
  dspace-api/src/test/java/org/dspace/content/RelationshipMetadataServiceIT.java
  dspace/config/spring/api/virtual-metadata.xml
Labels: 1 APPROVAL, component: configurable entities

#3034 Community admin should also be considered a Collection admin
  dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java
  dspace-api/src/test/java/org/dspace/authorize/AuthorizeServiceTest.java
Labels: 1 APPROVAL, authorization, bug

#3067 NullPointerException occurs when accessing WorkflowItem after deleting the Submitter
  dspace-api/src/test/java/org/dspace/builder/WorkflowItemBuilder.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/AInprogressItemConverter.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/eperson/DeleteEPersonSubmitterIT.java
Labels: 1 APPROVAL

#2746 Entities related to Entities of the same type
  dspace-api/src/main/java/org/dspace/content/RelationshipMetadataServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/RelationshipServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/dao/RelationshipDAO.java
  dspace-api/src/main/java/org/dspace/content/dao/impl/RelationshipDAOImpl.java
  dspace-api/src/main/java/org/dspace/content/service/RelationshipService.java
  dspace-api/src/test/java/org/dspace/handle/dao/impl/HandleDAOImplTest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RelationshipRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RelationshipRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RelationshipTypeRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/test/AbstractEntityIntegrationTest.java
  dspace/config/spring/api/core-services.xml
  dspace/config/spring/api/dublicore-metadata-mapper.xml
  dspace/config/spring/api/external-services.xml
  dspace/config/spring/api/workflow-actions.xml
  dspace/config/spring/rest/event-service-listeners.xml
Labels: bug, component: configurable entities

#3058 Fix obvious bug in SiteServiceInitializer
  dspace-api/src/main/java/org/dspace/storage/rdbms/SiteServiceInitializer.java
Labels: 1 APPROVAL, backend: FlywayDB, bug

#3083 Fix bug in cleanIndex() where not all Solr fields were returned.
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
Labels: 1 APPROVAL, bug, component: Discovery

#3085 Fix issues with OAI accidentally loading the wrong ConfigurationService
  dspace-oai/src/main/java/org/dspace/xoai/services/api/config/ConfigurationService.java
  dspace-oai/src/main/java/org/dspace/xoai/services/impl/cache/DSpaceXOAICacheService.java
  dspace-oai/src/main/java/org/dspace/xoai/services/impl/cache/DSpaceXOAILastCompilationCacheService.java
  dspace-oai/src/main/java/org/dspace/xoai/services/impl/config/DSpaceConfigurationService.java
Labels: 1 APPROVAL, bug, high priority, interface: OAI-PMH, interface: command-line

#3086 Addressing issue #3074
  dspace/config/crosswalks/oai/transformers/openaire4.xsl
Labels: 1 APPROVAL

#3068 Fixing internal server errors for external sources
  dspace-api/src/main/java/org/dspace/external/provider/impl/OrcidV3AuthorDataProvider.java
  dspace-api/src/main/java/org/dspace/external/provider/impl/SherpaJournalDataProvider.java
  dspace-api/src/main/java/org/dspace/external/provider/impl/SherpaPublisherDataProvider.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ExternalSourceRestRepository.java
Labels: 1 APPROVAL

#3079 3078 Change EntityTypeLabelRestController get by label to return REST…
  dspace-server-webapp/src/main/java/org/dspace/app/rest/EntityTypeLabelRestController.java
Labels: 1 APPROVAL

#3087 DS-4563 Signal that the transaction should be committed
  dspace-jspui/src/main/java/org/dspace/app/webui/servlet/admin/CurateServlet.java
Labels: bug, quick win

#3081 item-submission refactor to have different step xml tags
  dspace-api/src/main/java/org/dspace/app/util/SubmissionConfigReader.java
  dspace-api/src/test/data/dspaceFolder/config/item-submission.xml
  dspace-server-webapp/src/test/data/dspaceFolder/config/item-submission.xml
  dspace/config/item-submission.dtd
  dspace/config/item-submission.xml
Labels: 1 APPROVAL, component: submission, configuration

#3084 Discovery event consumer throwing ClassCastException on WorkspaceItem creation fix
  dspace-api/src/main/java/org/dspace/discovery/indexobject/AbstractIndexableObject.java
Labels: 1 APPROVAL, bug

#3091 Create Shibboleth Docker Scripts using samltest.id for easier development
  Dockerfile.test
  docker-compose.yml
  dspace/src/main/docker-compose/README.md
  dspace/src/main/docker-compose/docker-compose-shibboleth.yml
  dspace/src/main/docker/README.md
  dspace/src/main/docker/dspace-shibboleth/Dockerfile
  dspace/src/main/docker/dspace-shibboleth/attribute-map.xml
  dspace/src/main/docker/dspace-shibboleth/dspace-vhost.conf
  dspace/src/main/docker/dspace-shibboleth/httpd-shibd-foreground.sh
  dspace/src/main/docker/dspace-shibboleth/shibboleth2.xml
  pom.xml
Labels: 1 APPROVAL, authentication: Shibboleth, backend: Docker, new feature
