Repository DSpace/DSpace, pull requests merged in 2020-10, with the labels that each got.

#2979 Submission bugfix for file upload mandatory
  dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/UploadValidation.java
Labels: 1 APPROVAL, bug

#2949 Upgrade to Flyway v6.5.5. Update code based on Flyway API changes
  dspace-api/pom.xml
  dspace-api/src/main/java/org/dspace/core/Context.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/DatabaseRegistryUpdater.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/DatabaseUtils.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/FlywayUpgradeUtils.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/GroupServiceInitializer.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/PostgreSQLCryptoChecker.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/SiteServiceInitializer.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/MigrationUtils.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/V1_3_9__Drop_constraint_for_DSpace_1_4_schema.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/V1_5_9__Drop_constraint_for_DSpace_1_6_schema.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/V5_0_2014_09_25__DS_1582_Metadata_For_All_Objects_drop_constraint.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/V5_7_2017_05_05__DS_3431_Add_Policies_for_BasicWorkflow.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/V6_0_2015_03_06__DS_2701_Dso_Uuid_Migration.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/V6_0_2015_08_31__DS_2701_Hibernate_Workflow_Migration.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/V6_0_2016_01_26__DS_2188_Remove_DBMS_Browse_Tables.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/V6_1_2017_01_03__DS_3431_Add_Policies_for_BasicWorkflow.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/migration/V7_0_2018_04_03__Upgrade_Workflow_Policy.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/xmlworkflow/V5_0_2014_11_04__Enable_XMLWorkflow_Migration.java
  dspace-api/src/main/java/org/dspace/storage/rdbms/xmlworkflow/V6_0_2015_09_01__DS_2701_Enable_XMLWorkflow_Migration.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/XmlWorkflowServiceImpl.java
  dspace-api/src/main/resources/org/dspace/storage/rdbms/flywayupgrade/oracle/upgradeToFlyway4x.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/flywayupgrade/postgres/upgradeToFlyway4x.sql
  dspace-api/src/test/java/org/dspace/AbstractIntegrationTestWithDatabase.java
  dspace-api/src/test/java/org/dspace/AbstractUnitTest.java
Labels: backend: FlywayDB, code task, dependencies

#2978 Features endpoint: Community / collection creation
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/CreateCollectionFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/CreateCommunityFeature.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/CanCreateCollectionsIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/CanCreateCommunitiesIT.java
Labels: 1 APPROVAL, authorization, new feature

#2928 [DS-4036] Delete EPersons even if they are referenced
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemAuthorExtractor.java
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemHelpdeskStrategy.java
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemMetadataStrategy.java
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemSubmitterStrategy.java
  dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java
  dspace-api/src/main/java/org/dspace/authorize/ResourcePolicyServiceImpl.java
  dspace-api/src/main/java/org/dspace/authorize/dao/ResourcePolicyDAO.java
  dspace-api/src/main/java/org/dspace/authorize/dao/impl/ResourcePolicyDAOImpl.java
  dspace-api/src/main/java/org/dspace/authorize/service/AuthorizeService.java
  dspace-api/src/main/java/org/dspace/authorize/service/ResourcePolicyService.java
  dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/WorkspaceItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/dao/ItemDAO.java
  dspace-api/src/main/java/org/dspace/content/dao/impl/ItemDAOImpl.java
  dspace-api/src/main/java/org/dspace/content/service/ItemService.java
  dspace-api/src/main/java/org/dspace/eperson/EPersonCLITool.java
  dspace-api/src/main/java/org/dspace/eperson/EPersonDeletionException.java
  dspace-api/src/main/java/org/dspace/eperson/EPersonServiceImpl.java
  dspace-api/src/main/java/org/dspace/eperson/GroupServiceImpl.java
  dspace-api/src/main/java/org/dspace/eperson/service/GroupService.java
  dspace-api/src/main/java/org/dspace/workflow/WorkflowService.java
  dspace-api/src/main/java/org/dspace/workflowbasic/BasicWorkflowServiceImpl.java
  dspace-api/src/main/java/org/dspace/workflowbasic/TaskListItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/workflowbasic/dao/TaskListItemDAO.java
  dspace-api/src/main/java/org/dspace/workflowbasic/dao/impl/TaskListItemDAOImpl.java
  dspace-api/src/main/java/org/dspace/workflowbasic/service/TaskListItemService.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/XmlWorkflowServiceImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/AcceptEditRejectAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/ReviewAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/SingleUserReviewAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/userassignment/AssignOriginalSubmitterAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/userassignment/ClaimAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/PoolTaskServiceImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/WorkflowItemRoleServiceImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/service/PoolTaskService.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/service/WorkflowItemRoleService.java
  dspace-api/src/main/resources/Messages.properties
  dspace-api/src/test/java/org/dspace/builder/WorkspaceItemBuilder.java
  dspace-api/src/test/java/org/dspace/eperson/EPersonInWorkflowIT.java
  dspace-api/src/test/java/org/dspace/eperson/EPersonTest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/EPersonRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/EPersonRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/eperson/DeleteEPersonSubmitterIT.java
  dspace/config/dspace.cfg
  dspace/config/emails/request_item.to_admin
Labels: high priority

#2998 Fixes to Parent POM to resolve release issues with Beta 4
  pom.xml
Labels: code task, high priority

#3024 ROOT endpoint (/server) returns the version of DSpace
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/RootConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/RootRest.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/converter/RootConverterTest.java
Labels: 1 APPROVAL

#2999 Cleaning up the cache of Builders after each test
  dspace-api/src/test/java/org/dspace/AbstractIntegrationTestWithDatabase.java
  dspace-api/src/test/java/org/dspace/builder/AbstractBuilder.java
  dspace-api/src/test/java/org/dspace/builder/util/AbstractBuilderCleanupUtil.java
Labels: 1 APPROVAL, code task, hacktoberfest-accepted

#3021 Upgrade to latest commons configuration & opencsv
  dspace-api/pom.xml
  dspace-api/src/main/java/org/dspace/statistics/util/RepairDump.java
  pom.xml
Labels: 1 APPROVAL, bug, configuration, dependencies

#2993 Features endpoint: Download/RequestACopy features
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/DownloadFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/RequestCopyFeature.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/DownloadFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/RequestCopyFeatureIT.java
Labels: 1 APPROVAL, authorization, hacktoberfest-accepted

#3005 Features endpoint: Edit Collection Permissions
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ManageAdminGroupFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ManageSubmitterGroupFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ManageTemplateItemFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ManageWorkflowGroupFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/MoveFeature.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ManageAdminGroupFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ManageSubmitterGroupFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ManageTemplateItemFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ManageWorkflowGroupFeatureIT.java
Labels: 1 APPROVAL, authorization, hacktoberfest-accepted

#3013 Features Endpoint: Permissions to view stats, map items, see versions
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ManageMappedItemsFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ViewSearchStatisticsFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ViewUsageStatisticsFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ViewVersionsFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ViewWorkflowStatisticsFeature.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ManageMappedItemsFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ViewSearchStatisticsFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ViewUsageStatisticsFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ViewVersionsFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ViewWorkflowStatisticsFeatureIT.java
Labels: 1 APPROVAL, authorization, hacktoberfest-accepted
