Repository DSpace/DSpace, pull requests merged in 2020-07, with the labels that each got.

#2812 DS-3679 E-Mail Configuration not valid if mail.server.username is not specified
  dspace-services/src/main/java/org/dspace/services/email/EmailServiceImpl.java
  dspace-services/src/test/java/org/dspace/services/email/EmailServiceImplTest.java
Labels: 1 APPROVAL, bug, high priority

#2784 DS-4466 REST API should obtain language settings from Client
  dspace-api/src/main/java/org/dspace/administer/CreateAdministrator.java
  dspace-api/src/main/java/org/dspace/core/Context.java
  dspace-api/src/main/java/org/dspace/core/I18nUtil.java
  dspace-api/src/test/data/dspaceFolder/config/item-submission.xml
  dspace-api/src/test/data/dspaceFolder/config/submission-forms_it.xml
  dspace-api/src/test/data/dspaceFolder/config/submission-forms_uk.xml
  dspace-api/src/test/java/org/dspace/core/ContextTest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/filter/ContentLanguageHeaderResponseFilter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/AbstractDSpaceRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/SubmissionFormRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/SubmissionUploadRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/LanguageSupportIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/SubmissionFormsControllerIT.java
Labels: 1 APPROVAL, REST API v7

#2854 Replace all references to `master` with `main`
  .github/pull_request_template.md
  Dockerfile
  Dockerfile.cli
  Dockerfile.test
  README.md
  dspace-api/src/main/java/org/dspace/disseminate/service/CitationDocumentService.java
  dspace-api/src/main/java/org/dspace/importer/external/metadatamapping/contributor/SimpleXpathMetadatumContributor.java
  dspace-rest/src/main/webapp/WEB-INF/applicationContext.xml
  dspace-server-webapp/src/main/java/org/dspace/app/rest/Application.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/Utils.java
  dspace/config/crosswalks/google-metadata.properties
  dspace/src/main/docker-compose/cli.ingest.yml
  dspace/src/main/docker/README.md
  pom.xml
Labels: code task, configuration

#2861 Automatically add new Issues to "DSpace Backlog" project board
  .github/workflows/issue_opened.yml
Labels: code task

#2857 Auto Assign new Pull Requests to "main" branch to the PR creator
  .github/workflows/pull_request_opened.yml
Labels: code task

#2831 beta4 - IP Authentication Support
  dspace-api/src/test/data/dspaceFolder/config/local.cfg
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/AnonymousAdditionalAuthorizationFilter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/AnonymousAdditionalAuthorizationFilterIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/test/AbstractControllerIntegrationTest.java
Labels: 1 APPROVAL, authorization, e/12

#2245 Remove unused jackson dependencies from DSpace 5.x OAI
  dspace-oai/pom.xml
Labels: code task

#2386 [DS-4200] IPMatcher: Fix netmask conversion
  dspace-api/src/main/java/org/dspace/authenticate/IPMatcher.java
  dspace-api/src/test/java/org/dspace/authenticate/IPMatcherTest.java
Labels: authorization, bug, port to 6.x, quick win

#2862 DS-4534 fix for Anonymous as a sub-group.
  dspace-api/src/main/java/org/dspace/eperson/GroupServiceImpl.java
Labels: 1 APPROVAL, authorization, bug, quick win

#2828 [DS-4205] Bump Handle to version 9.3.0-SNAPSHOT
  dspace-api/pom.xml
  dspace-server-webapp/pom.xml
  dspace/config/log4j-handle-plugin.properties
  dspace/modules/server/pom.xml
  pom.xml
Labels: high priority, identifier: Handles, improvement

#2867 DS-4527: Authorizations endpoint and X-On-Behalf-Of headers
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/AuthorizationRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthorizationRestRepositoryIT.java
Labels: 1 APPROVAL, e/12

#2113 DS-3945: XMLUI: filtering by "starts with" field twice on browsing pages doesn't work
  dspace-xmlui/src/main/java/org/dspace/app/xmlui/aspect/artifactbrowser/ConfigurableBrowse.java
Labels: bug, interface: XMLUI, question, quick win

#2904 Fixes for several LGTM reported severe bugs
  dspace-api/src/main/java/org/dspace/app/itemimport/ItemImportServiceImpl.java
  dspace-api/src/main/java/org/dspace/app/sherpa/SHERPAResponse.java
  dspace-api/src/main/java/org/dspace/content/BitstreamFormatServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/MetadataField.java
  dspace-api/src/main/java/org/dspace/content/MetadataSchema.java
  dspace-api/src/main/java/org/dspace/content/MetadataValue.java
  dspace-api/src/main/java/org/dspace/content/WorkspaceItem.java
  dspace-api/src/main/java/org/dspace/content/packager/METSManifest.java
  dspace-api/src/main/java/org/dspace/ctask/general/MetadataWebService.java
  dspace-api/src/main/java/org/dspace/harvest/HarvestScheduler.java
  dspace-api/src/main/java/org/dspace/license/CCLicenseConnectorServiceImpl.java
  dspace-api/src/main/java/org/dspace/rdf/negotiation/Negotiator.java
  dspace-api/src/main/java/org/dspace/submit/lookup/ArXivService.java
  dspace-api/src/main/java/org/dspace/submit/lookup/CiNiiService.java
  dspace-api/src/main/java/org/dspace/submit/lookup/CrossRefService.java
  dspace-api/src/main/java/org/dspace/submit/lookup/PubmedService.java
  dspace-api/src/main/java/org/dspace/versioning/Version.java
  dspace-api/src/main/java/org/dspace/versioning/VersionHistory.java
  dspace-rdf/src/main/java/org/dspace/rdf/providing/LocalURIRedirectionServlet.java
  dspace-rest/src/main/webapp/static/reports/restReport.js
  dspace-server-webapp/src/main/java/org/dspace/app/rest/OpenSearchController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/PoolTaskRestPermissionEvaluatorPlugin.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/jwt/JWTTokenRestAuthenticationServiceImpl.java
  dspace-sword/src/main/java/org/dspace/sword/DepositManager.java
Labels: 1 APPROVAL, bug, code task

#2903 Add error logging & fix "Information exposure through a stack trace" error reported by LGTM
  dspace-server-webapp/src/main/java/org/dspace/app/rest/exception/DSpaceApiExceptionControllerAdvice.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/DSpace401AuthenticationEntryPoint.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessAuthenticationFilter.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/WorkflowDefinitionRestRepositoryIT.java
  dspace-sword/src/main/java/org/purl/sword/server/ServiceDocumentServlet.java
Labels: 1 APPROVAL, REST API v7, bug

#2907 Bump Handle to version 9.3.0 final.
  pom.xml
Labels: 1 APPROVAL, dependencies, identifier: Handles

#2859 [DS-4149] support for additional "metadata" insertion on "item.compile" solr document field from external plugin (6.x)
  dspace-oai/pom.xml
  dspace-oai/src/main/java/org/dspace/xoai/app/CCElementAdditional.java
  dspace-oai/src/main/java/org/dspace/xoai/app/OAISpringLoader.java
  dspace-oai/src/main/java/org/dspace/xoai/app/OrcidVirtualElementAdditional.java
  dspace-oai/src/main/java/org/dspace/xoai/app/PermissionElementAdditional.java
  dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java
  dspace-oai/src/main/java/org/dspace/xoai/app/XOAIItemCompilePlugin.java
  dspace-oai/src/main/java/org/dspace/xoai/services/impl/resources/DSpaceResourceResolver.java
  dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java
  dspace-oai/src/test/java/org/dspace/xoai/tests/stylesheets/AbstractXSLTest.java
  dspace/config/crosswalks/oai/metadataFormats/mets.xsl
  dspace/config/modules/spring.cfg
  dspace/config/spring/oai/oai.xml
Labels: interface: OAI-PMH, new feature, quick win

#2728 DS-4211: Set Item iterator to emptyIterator() so that it's never null (7.x)
  dspace-api/src/main/java/org/dspace/content/MetadataDSpaceCsvExportServiceImpl.java
Labels: bug, quick win, tools: export

#2667 Entities Configure search configurations matching name
  dspace-api/src/test/data/dspaceFolder/config/submission-forms.xml
  dspace-server-webapp/src/test/java/org/dspace/app/rest/SubmissionFormsControllerIT.java
  dspace/config/spring/api/discovery.xml
  dspace/config/submission-forms.xml
Labels: REST API v7, component: configurable entities, improvement

#2745 Removed the RelationshipTypeId from Relationship endpoints
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/RelationshipRest.java
Labels: component: configurable entities

#2908 Ensure ShibbolethRestController only redirects to trusted URLs after authentication
  dspace-server-webapp/src/main/java/org/dspace/app/rest/ShibbolethRestController.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ShibbolethRestControllerIT.java
Labels: 1 APPROVAL, authentication: Shibboleth, bug

#2820 Curation tasks using the scripts and processes functionality
  dspace-api/src/main/java/org/dspace/curate/CurationCli.java
  dspace-api/src/main/java/org/dspace/curate/CurationClientOptions.java
  dspace-api/src/main/java/org/dspace/curate/CurationScriptConfiguration.java
  dspace-api/src/main/java/org/dspace/curate/Curator.java
  dspace-api/src/test/data/dspaceFolder/assetstore/curate.txt
  dspace-api/src/test/data/dspaceFolder/config/spring/api/scripts.xml
  dspace-api/src/test/java/org/dspace/curate/CuratorTest.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ScriptRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/curate/CurationScriptIT.java
  dspace-server-webapp/src/test/resources/test-config.properties
  dspace/config/launcher.xml
  dspace/config/modules/curate.cfg
  dspace/config/spring/api/scripts.xml
Labels: tools: curation-tasks

#2913 (Integration Tests) Fix response checks to no longer expect specific error messages
  dspace-server-webapp/src/test/java/org/dspace/curate/CurationScriptIT.java
Labels: 1 APPROVAL, bug, code task, high priority
