Repository DSpace/DSpace, pull requests merged in 2021-12, with the labels that each got.

#8032 Fix issue where Shibboleth Authentication was creating two temporary Auth Cookies
  dspace-api/src/main/java/org/dspace/authenticate/ShibAuthentication.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/ShibbolethRestController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/DSpaceAuthentication.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/EPersonRestAuthenticationProvider.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/ShibbolethAuthenticationFilter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/ShibbolethLoginFilter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessAuthenticationFilter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessLoginFilter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WebSecurityConfiguration.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/jwt/JWTTokenHandler.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/jwt/JWTTokenRestAuthenticationServiceImpl.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthenticationRestControllerIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/security/ShibbolethLoginFilterIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/security/jwt/JWTTokenHandlerTest.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/security/jwt/ShortLivedJWTTokenHandlerTest.java
Labels: bug, code task, authentication: Shibboleth, 1 APPROVAL

#8031 Fix unstable / randomly failing IT methods in AuthenticationRestControllerIT
  dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthenticationRestControllerIT.java
Labels: bug, code task, high priority, 1 APPROVAL, testing framework

#8034 Fix condition for metadata validation if is Authority Controlled
  dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/MetadataValidation.java
Labels: bug, 1 APPROVAL, component: authority control

#8058 Add GitHub action to build Docker images and push to DockerHub
  .github/workflows/build.yml
  .github/workflows/docker.yml
  dspace/src/main/docker/README.md
Labels: configuration, backend: Docker

#8059 Disable Docker image build action on forked repos & on non-maintenance branches
  .github/workflows/docker.yml
Labels: code task, backend: Docker

#8061 Cleanup our LICENSE file so GitHub can detect our BSD license
  LICENSE
  NOTICE
  README.md
Labels: code task

#8045 Avoid incorrect sort
  dspace-api/src/main/java/org/dspace/content/DSpaceObjectServiceImpl.java
Labels: bug, 1 APPROVAL

#8025 Add migration to fix metadatavalue.place
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/h2/V7.1_2021.10.18__Fix_MDV_place_after_migrating_from_DSpace_5.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/oracle/V7.1_2021.10.18__Fix_MDV_place_after_migrating_from_DSpace_5.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.1_2021.10.18__Fix_MDV_place_after_migrating_from_DSpace_5.sql
Labels: bug, high priority, backend: FlywayDB

#8069 Update dependencies in Dockerfiles
  Dockerfile
  Dockerfile.cli
  Dockerfile.test
  docker-compose.yml
Labels: backend: Docker, dependencies

#8044 [CST-4882] The search loads indefinitely if the written query is invalid
  dspace-server-webapp/src/main/java/org/dspace/app/rest/DiscoveryRestController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/DiscoveryRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
Labels: bug, high priority, component: Discovery

#8051 Rely on https handle.net urls instead of http ones
  dspace-api/src/main/java/org/dspace/handle/HandleServiceImpl.java
  dspace-api/src/main/java/org/dspace/handle/service/HandleService.java
  dspace-api/src/main/java/org/dspace/harvest/OAIHarvester.java
  dspace/config/dspace.cfg
  dspace/config/local.cfg.EXAMPLE
Labels: configuration, identifier: Handles, 1 APPROVAL

#8057 IRUS patch performance improvements by adding a timeout
  dspace-api/src/main/java/org/dspace/statistics/export/service/OpenUrlServiceImpl.java
  dspace-api/src/test/java/org/dspace/statistics/export/service/OpenUrlServiceImplTest.java
Labels: bug, 1 APPROVAL

#8067 Fix findSubmitAuthorized endpoint to support queries by starts with
  dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java
Labels: bug, component: Discovery, 1 APPROVAL

#8082 test case in InstallItemTest expects wrong Exception to be thrown
  dspace-api/src/test/java/org/dspace/content/InstallItemTest.java
Labels: bug, code task

#8084 Rename LICENSE_HEADER to LICENSE.header and update all references
  LICENSE.header
  dspace/src/main/assembly/assembly.xml
  pom.xml
Labels: code task

#8068 dspace-angular issue 852 BrowseBy list are statically configured
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/BrowseIndexConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/BrowseIndexRest.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/BrowseIndexMatcher.java
Labels: bug, component: Discovery, 1 APPROVAL

#8046 Fixed context's mode handling to improve performances
  dspace-api/src/main/java/org/dspace/core/Context.java
  dspace-api/src/main/resources/spring/spring-dspace-core-services.xml
  dspace-api/src/test/java/org/dspace/AbstractIntegrationTestWithDatabase.java
Labels: bug, high priority, component: Discovery

#8089 Tag GoogleRecorderEventListener as deprecated
  dspace-api/src/main/java/org/dspace/google/GoogleRecorderEventListener.java
Labels: code task, quick win, component: statistics
