Repository DSpace/DSpace, pull requests merged in 2021-06, with the labels that each got.

#3285 Update license Bitstream format description
  dspace/config/registries/bitstream-formats.xml
Labels: 1 APPROVAL, configuration

#3280 Values escaped in browse and discover links
  dspace-server-webapp/src/main/java/org/dspace/app/rest/link/BrowseEntryHalLinkFactory.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/link/search/SearchFacetValueHalLinkFactory.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/FacetValueMatcher.java
Labels: bug, component: Discovery, medium priority

#2756 [DS-4149] porting XOAI additional indexer
  dspace-oai/src/main/java/org/dspace/xoai/app/CCElementItemCompilePlugin.java
  dspace-oai/src/main/java/org/dspace/xoai/app/OAISpringLoader.java
  dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java
  dspace-oai/src/main/java/org/dspace/xoai/app/XOAIExtensionItemCompilePlugin.java
  dspace-oai/src/main/java/org/dspace/xoai/util/ItemUtils.java
  dspace/config/crosswalks/oai/metadataFormats/oai_openaire.xsl
  dspace/config/modules/spring.cfg
  dspace/config/spring/oai/oai.xml
Labels: improvement, interface: OAI-PMH

#3277 Delete item as collection admin & related issues
  dspace-api/src/main/java/org/dspace/content/BundleServiceImpl.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ItemRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/BundleRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RelationshipDeleteRestRepositoryIT.java
Labels: 1 APPROVAL, authorization, bug, high priority

#3288 Can't save more than one bitstream's access conditions during submission
  dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/factory/impl/BitstreamResourcePolicyAddPatchOperation.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/factory/impl/BitstreamResourcePolicyReplacePatchOperation.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/factory/impl/BitstreamResourcePolicyUtils.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/WorkspaceItemRestRepositoryIT.java
Labels: 1 APPROVAL, component: submission

#3300 Bugfix to usage report rest permission evaluator plugin
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/UsageReportRestPermissionEvaluatorPlugin.java
Labels: 1 APPROVAL, bug

#3297 Increase default thumbnail size to match with UI display settings
  dspace/config/dspace.cfg
Labels: 1 APPROVAL, configuration

#3264 Need a way to identify withdrawn items via REST API
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/ItemConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ItemRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ItemVersionLinkRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/AuthorizeServicePermissionEvaluatorPlugin.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/DSpaceRestPermission.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java
Labels: 1 APPROVAL, improvement, low priority

#3304 Searches without a scope can trigger "Invalid UUID" error from ScopeResolver
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/SearchEventConverter.java
Labels: 1 APPROVAL, bug, component: Discovery, component: statistics

#3307 Remove unimplemented interface CacheProvider and all references to it
  dspace-services/src/main/java/org/dspace/providers/CacheProvider.java
  dspace-services/src/main/java/org/dspace/providers/package-info.java
  dspace-services/src/main/java/org/dspace/services/caching/CachingServiceImpl.java
Labels: 1 APPROVAL, bug

#3157 Implement curation tasks for Configurable Workflow
  dspace-api/pom.xml
  dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/CommunityServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/DSpaceObject.java
  dspace-api/src/main/java/org/dspace/core/AbstractHibernateDAO.java
  dspace-api/src/main/java/org/dspace/core/Context.java
  dspace-api/src/main/java/org/dspace/curate/Curator.java
  dspace-api/src/main/java/org/dspace/curate/XmlWorkflowCuratorServiceImpl.java
  dspace-api/src/main/java/org/dspace/curate/package-info.java
  dspace-api/src/main/java/org/dspace/curate/service/XmlWorkflowCuratorService.java
  dspace-api/src/main/java/org/dspace/service/DSpaceCRUDService.java
  dspace-api/src/main/java/org/dspace/workflow/CurationTaskConfig.java
  dspace-api/src/main/java/org/dspace/workflow/FlowStep.java
  dspace-api/src/main/java/org/dspace/workflow/Task.java
  dspace-api/src/main/java/org/dspace/workflow/TaskSet.java
  dspace-api/src/main/java/org/dspace/workflow/WorkflowItemService.java
  dspace-api/src/main/java/org/dspace/workflow/WorkflowService.java
  dspace-api/src/main/java/org/dspace/workflow/package-info.java
  dspace-api/src/main/java/org/dspace/workflow/package.html
  dspace-api/src/main/java/org/dspace/xmlworkflow/WorkflowUtils.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/XmlWorkflowFactoryImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/XmlWorkflowServiceImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/package-info.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/service/WorkflowRequirementsService.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/service/XmlWorkflowService.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/Step.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/Workflow.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/Action.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/ActionInterface.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/ActionResult.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/package-info.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/ProcessingAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/userassignment/UserSelectionAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/package-info.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/dao/ClaimedTaskDAO.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/package-info.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/storedcomponents/service/ClaimedTaskService.java
  dspace-api/src/main/resources/Messages.properties
  dspace-api/src/main/resources/org/dspace/workflow/workflow-curation.xsd
  dspace-api/src/test/data/dspaceFolder/config/modules/curate.cfg
  dspace-api/src/test/data/dspaceFolder/config/spring/api/workflow.xml
  dspace-api/src/test/data/dspaceFolder/config/workflow-curation.xml
  dspace-api/src/test/java/org/dspace/builder/AbstractBuilder.java
  dspace-api/src/test/java/org/dspace/builder/CollectionBuilder.java
  dspace-api/src/test/java/org/dspace/builder/EPersonBuilder.java
  dspace-api/src/test/java/org/dspace/builder/WorkflowItemBuilder.java
  dspace-api/src/test/java/org/dspace/ctask/testing/MarkerTask.java
  dspace-api/src/test/java/org/dspace/ctask/testing/package-info.java
  dspace-api/src/test/java/org/dspace/util/DSpaceConfigurationInitializer.java
  dspace-api/src/test/java/org/dspace/util/DSpaceKernelInitializer.java
  dspace-api/src/test/java/org/dspace/workflow/CurationTaskConfigTest.java
  dspace-api/src/test/java/org/dspace/workflow/WorkflowCurationIT.java
  dspace-api/src/test/java/org/dspace/xmlworkflow/state/actions/processingaction/NoAction.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/TaskRestRepositoriesIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/WorkflowDefinitionRestRepositoryIT.java
  dspace/config/spring/api/core-services.xml
  dspace/config/spring/api/workflow.xml
  dspace/config/workflow-curation.xml
Labels: component: workflow, medium priority, new feature, tools: curation-tasks

#3301 Update our GitHub CI settings to upload all test output to a downloadable artifact whenever a test failure occurs.
  .github/workflows/build.yml
Labels: 1 APPROVAL, code task

#3308 W2p 80239 pdf box thumbnail fix
  dspace-api/src/main/java/org/dspace/app/mediafilter/PDFBoxThumbnail.java
Labels: 1 APPROVAL, bug, high priority, tools: media-filters

#3313 Fix JAXB build errors by disabling package annotations.
  dspace-api/pom.xml
Labels: 1 APPROVAL, bug, configuration, high priority

#3309 Add endpoints for Item/Bitstream thumbnails
  dspace-api/src/main/java/org/dspace/content/BitstreamServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/service/BitstreamService.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/BitstreamRest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/ItemRest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/BitstreamThumbnailLinkRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ItemThumbnailLinkRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/BitstreamRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/BitstreamMatcher.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/ItemMatcher.java
Labels: medium priority
