Repository DSpace/DSpace, pull requests merged in 2021-04, with the labels that each got.

#3200 Mapped Items not visible in Collection browse
  dspace-api/src/main/java/org/dspace/discovery/IndexEventConsumer.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/MappedCollectionRestRepositoryIT.java
Labels: 1 APPROVAL, bug, merge conflict

#3160 Metadata field caching hibernate performance
  dspace-api/src/main/java/org/dspace/content/dao/impl/MetadataFieldDAOImpl.java
  dspace-api/src/test/java/org/dspace/content/MetadataFieldPerformanceTest.java
  dspace-api/src/test/java/org/dspace/content/service/MetadataFieldServiceTest.java
Labels: bug, performance / caching

#3148 Getting 401 when Community or Collection Administrator tries to edit Collection Authorization Group
  dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java
  dspace-api/src/main/java/org/dspace/authorize/service/AuthorizeService.java
  dspace-api/src/main/java/org/dspace/discovery/SolrServicePrivateItemPlugin.java
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceResourceRestrictionPlugin.java
  dspace-api/src/test/java/org/dspace/authorize/AuthorizeServiceTest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/CollectionAdminFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ComColAdminFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/CommunityAdminFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/ManageGroupsFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/CollectionRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/CommunityRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/EPersonRestAuthenticationProvider.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/EPersonRestPermissionEvaluatorPlugin.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/GroupRestPermissionEvaluatorPlugin.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessAuthenticationFilter.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/CollectionRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/CommunityRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/CollectionAdminFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ComColAdminFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/CommunityAdminFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/ManageGroupsFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/security/EPersonRestAuthenticationProviderTest.java
  dspace/config/spring/api/discovery.xml
Labels: authorization, bug, high priority

#3183 Rename / move 'relationship.type' metadata field to 'dspace.entity.type'
  dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataImport.java
  dspace-api/src/main/java/org/dspace/content/EntityServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/RelationshipMetadataServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/RelationshipServiceImpl.java
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/oracle/V7.0_2021.03.18__Move_entity_type_to_dspace_schema.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.0_2021.03.18__Move_entity_type_to_dspace_schema.sql
  dspace-api/src/test/java/org/dspace/app/bulkedit/MetadataImportIT.java
  dspace-api/src/test/java/org/dspace/app/csv/CSVMetadataImportReferenceIT.java
  dspace-api/src/test/java/org/dspace/builder/ItemBuilder.java
  dspace-api/src/test/java/org/dspace/builder/WorkspaceItemBuilder.java
  dspace-api/src/test/java/org/dspace/content/EntityServiceImplTest.java
  dspace-api/src/test/java/org/dspace/content/RelationshipMetadataServiceIT.java
  dspace-api/src/test/java/org/dspace/content/RelationshipServiceImplPlaceTest.java
  dspace-api/src/test/java/org/dspace/content/RelationshipServiceImplTest.java
  dspace-api/src/test/java/org/dspace/content/dao/RelationshipDAOImplTest.java
  dspace-api/src/test/java/org/dspace/content/dao/RelationshipTypeDAOImplTest.java
  dspace-api/src/test/java/org/dspace/statistics/export/ITIrusExportUsageEventListener.java
  dspace-api/src/test/java/org/dspace/statistics/export/processor/ExportEventProcessorIT.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/ItemConverter.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ItemRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/PatchMetadataIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RelationshipDeleteRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RelationshipRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RelationshipTypeRestControllerIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/WorkspaceItemRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/csv/CsvExportIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/csv/CsvImportIT.java
  dspace/config/crosswalks/oai/xoai.xml
  dspace/config/registries/dspace-types.xml
  dspace/config/registries/relationship-formats.xml
  dspace/config/spring/api/discovery.xml
Labels: 1 APPROVAL, code task

#3218 Proper Bean-like initialization of SherpaService
  dspace-api/pom.xml
  dspace-api/src/main/java/org/dspace/app/sherpa/SHERPAService.java
Labels: 1 APPROVAL, bug, code task

#3171 Update IP-based security configurations to more sane defaults (now that CORS + CSRF are enabled)
  dspace-api/pom.xml
  dspace-api/src/main/java/org/dspace/core/Utils.java
  dspace-api/src/main/java/org/dspace/service/impl/ClientInfoServiceImpl.java
  dspace-api/src/main/java/org/dspace/statistics/util/IPTable.java
  dspace-api/src/test/java/org/dspace/core/UtilsTest.java
  dspace-api/src/test/java/org/dspace/service/impl/ClientInfoServiceImplTest.java
  dspace-api/src/test/java/org/dspace/statistics/util/IPTableTest.java
  dspace-oai/pom.xml
  dspace-server-webapp/pom.xml
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/jwt/JWTTokenHandler.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/jwt/LoginJWTTokenHandler.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/jwt/ShortLivedJWTTokenHandler.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/AnonymousAdditionalAuthorizationFilterIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthenticationRestControllerIT.java
  dspace-services/pom.xml
  dspace-services/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  dspace/config/dspace.cfg
  dspace/config/local.cfg.EXAMPLE
  dspace/config/modules/authentication.cfg
  dspace/config/modules/rest.cfg
  dspace/modules/additions/pom.xml
  dspace/modules/server/pom.xml
  pom.xml
Labels: bug, configuration

#3195 Added script to delete all metadata values
  dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataDeletion.java
  dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataDeletionCli.java
  dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataDeletionCliScriptConfiguration.java
  dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataDeletionScriptConfiguration.java
  dspace-api/src/test/data/dspaceFolder/config/spring/api/scripts.xml
  dspace-api/src/test/java/org/dspace/app/bulkedit/MetadataDeletionIT.java
  dspace-api/src/test/java/org/dspace/app/scripts/handler/impl/TestDSpaceRunnableHandler.java
  dspace-server-webapp/src/test/data/dspaceFolder/config/spring/rest/scripts.xml
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ScriptRestRepositoryIT.java
  dspace/config/modules/bulkedit.cfg
  dspace/config/spring/api/scripts.xml
  dspace/config/spring/rest/scripts.xml
Labels: 1 APPROVAL, tools: processes

#3219 Restrict /api/system/scripts endpoint to admin-only
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ScriptRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ScriptRestRepositoryIT.java
Labels: 1 APPROVAL, REST API v7, authorization, bug, tools: processes

#3134 Designate "tilted" relationships to improve performance
  dspace-api/src/main/java/org/dspace/app/util/InitializeEntities.java
  dspace-api/src/main/java/org/dspace/content/EntityServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/RelationshipMetadataServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/RelationshipServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/RelationshipType.java
  dspace-api/src/main/java/org/dspace/content/RelationshipTypeServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/dao/RelationshipDAO.java
  dspace-api/src/main/java/org/dspace/content/dao/impl/RelationshipDAOImpl.java
  dspace-api/src/main/java/org/dspace/content/service/RelationshipService.java
  dspace-api/src/main/java/org/dspace/content/service/RelationshipTypeService.java
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/h2/V7.0_2021.02.08__tilted_rels.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/oracle/V7.0_2021.02.08__tilted_rels.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.0_2021.02.08__tilted_rels.sql
  dspace-api/src/test/data/dspaceFolder/config/entities/relationship-types.dtd
  dspace-api/src/test/java/org/dspace/content/LeftTiltedRelationshipMetadataServiceIT.java
  dspace-api/src/test/java/org/dspace/content/RelationshipMetadataServiceIT.java
  dspace-api/src/test/java/org/dspace/content/RelationshipServiceImplTest.java
  dspace-api/src/test/java/org/dspace/content/RightTiltedRelationshipMetadataServiceIT.java
  dspace-api/src/test/java/org/dspace/content/dao/RelationshipDAOImplTest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ItemRelationshipLinkRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/LeftTiltedRelationshipRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RelationshipRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RightTiltedRelationshipRestRepositoryIT.java
  dspace/config/entities/relationship-types.dtd
Labels: REST API v7, component: configurable entities

#3222 Collection location is not indexed for in submission items
  dspace-api/src/main/java/org/dspace/discovery/indexobject/InprogressSubmissionIndexFactoryImpl.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
Labels: 1 APPROVAL, bug, component: submission, component: workflow, e/1

#3223 CSRF short lived token GET endpoint
  dspace-api/src/main/java/org/dspace/service/ClientInfoService.java
  dspace-api/src/main/java/org/dspace/service/impl/ClientInfoServiceImpl.java
  dspace-api/src/test/data/dspaceFolder/config/local.cfg
  dspace-server-webapp/src/main/java/org/dspace/app/rest/AuthenticationRestController.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthenticationRestControllerIT.java
Labels: high priority

#3212 Fix #3211 by depending directly on tika-parsers
  dspace-api/pom.xml
  pom.xml
Labels: 1 APPROVAL, bug, dependencies

#3192 Replace new uses of Log4J v1 with v2. Ban v1 artifacts. #3190.
  dspace-api/pom.xml
  dspace-api/src/main/java/org/dspace/app/launcher/ScriptLauncher.java
  dspace-api/src/main/java/org/dspace/app/sherpa/v2/SHERPAPublisherResponse.java
  dspace-api/src/main/java/org/dspace/app/sherpa/v2/SHERPAResponse.java
  dspace-api/src/main/java/org/dspace/content/Bitstream.java
  dspace-api/src/main/java/org/dspace/content/Item.java
  dspace-api/src/main/java/org/dspace/discovery/SolrSearchCore.java
  dspace-api/src/main/java/org/dspace/external/service/impl/ExternalDataServiceImpl.java
  dspace-api/src/main/java/org/dspace/statistics/AnonymizeStatistics.java
  dspace-api/src/main/java/org/dspace/statistics/export/IrusExportUsageEventListener.java
  dspace-api/src/main/java/org/dspace/statistics/export/processor/ExportEventProcessor.java
  dspace-api/src/main/java/org/dspace/statistics/export/service/OpenUrlServiceImpl.java
  dspace-api/src/main/java/org/dspace/util/SolrUpgradePre6xStatistics.java
  dspace-api/src/test/java/org/dspace/builder/EntityTypeBuilder.java
  dspace-api/src/test/java/org/dspace/builder/RelationshipBuilder.java
  dspace-api/src/test/java/org/dspace/builder/RelationshipTypeBuilder.java
  dspace-api/src/test/java/org/dspace/builder/ResourcePolicyBuilder.java
  dspace-api/src/test/java/org/dspace/statistics/export/ITIrusExportUsageEventListener.java
  dspace-api/src/test/java/org/dspace/statistics/export/ITRetryFailedOpenUrlTracker.java
  dspace-oai/pom.xml
  dspace-server-webapp/src/main/java/org/dspace/app/rest/IdentifierRestController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/MappedCollectionRestController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/OpenSearchController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/UUIDLookupRestController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/CreateBitstreamFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/MoveFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/RequestCopyFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/ConverterService.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/DiscoverFacetsConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/DiscoverResultConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/VersionConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ClaimedTaskRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/EPersonRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ItemRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/PoolTaskRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ProcessRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RelationshipRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/WorkflowItemRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/AnonymousAdditionalAuthorizationFilter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/step/validation/LicenseValidation.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/RestRepositoryUtils.java
  pom.xml
Labels: 1 APPROVAL, code task, dependencies, error handling

#3224 Patch Add entire array with virtual values does not work
  dspace-api/src/main/java/org/dspace/content/DSpaceObjectServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/service/DSpaceObjectService.java
  dspace-api/src/main/java/org/dspace/content/service/ItemService.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/submit/factory/impl/ItemMetadataValueAddPatchOperation.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/PatchMetadataIT.java
Labels: high priority

#3235 Ensure a REST API running in Docker always trusts requests from the host machine
  docker-compose.yml
  dspace/src/main/docker-compose/local.cfg
Labels: backend: Docker, bug

#3225 Update links to Entities test data
  dspace/src/main/docker-compose/cli.assetstore.yml
  dspace/src/main/docker-compose/db.entities.yml
Labels: 1 APPROVAL, backend: Docker

#3237 Remove sequences which no longer exist from 'updatesequences' command
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/oracle/update-sequences.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/update-sequences.sql
Labels: bug

#3236 Exclude swagger-jersey-jaxrs as it would include old v1 jersey depenies
  dspace-api/pom.xml
Labels: high priority

#3238 Update Entity relationship types to remove non-zero cardinalities
  dspace/config/entities/relationship-types.xml
Labels: 1 APPROVAL, configuration

#3239 Fixed itemimport working dir configuration. #3163
  dspace-api/src/main/java/org/dspace/app/itemimport/ItemImportServiceImpl.java
Labels: 1 APPROVAL, bug, high priority, interface: command-line, tools: import

#2713 DS-4457 Avoid smtp authentication by default
  dspace/config/dspace.cfg
Labels: backend: email-system, bug, configuration

#3242 Fix broken Shibboleth Authentication & enhance tests & comments
  dspace-api/src/main/java/org/dspace/authenticate/ShibAuthentication.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/ShibbolethRestController.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/RestAuthenticationService.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/ShibbolethAuthenticationFilter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessAuthenticationFilter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/StatelessLoginFilter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/jwt/JWTTokenRestAuthenticationServiceImpl.java
  dspace-server-webapp/src/main/webapp/login.html
  dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthenticationRestControllerIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ShibbolethRestControllerIT.java
Labels: authentication: Shibboleth, bug, high priority

#3255 Update DS7 installation url
  README.md
Labels: documentation
