Repository DSpace/DSpace, pull requests merged in 2022-12, with the labels that each got.

#8583 Require javadocs for all public methods. Fix checkstyle errors.
  checkstyle.xml
  dspace-api/src/main/java/org/dspace/external/OpenAIRERestConnector.java
  dspace-api/src/main/java/org/dspace/external/provider/impl/LiveImportDataProvider.java
  dspace-api/src/main/java/org/dspace/importer/external/bibtex/service/BibtexImportMetadataSourceServiceImpl.java
  dspace-api/src/main/java/org/dspace/importer/external/liveimportclient/service/LiveImportClient.java
  dspace-api/src/main/java/org/dspace/importer/external/metadatamapping/contributor/EpoIdMetadataContributor.java
  dspace-api/src/main/java/org/dspace/importer/external/metadatamapping/contributor/SimpleJsonPathMetadataContributor.java
  dspace-api/src/main/java/org/dspace/importer/external/ris/service/RisImportMetadataSourceServiceImpl.java
  dspace-api/src/main/java/org/dspace/importer/external/service/components/AbstractPlainMetadataSource.java
  dspace-api/src/main/java/org/dspace/importer/external/service/components/FileSource.java
  dspace-api/src/main/java/org/dspace/scripts/Process.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/RestAuthenticationService.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/ClaimedTaskMatcher.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/PoolTaskMatcher.java
  dspace-services/src/main/java/org/dspace/services/RequestService.java
Labels: code task, 1 APPROVAL

#8597 Fix broken OrcidQueueConsumerIT & several other flakey tests
  dspace-api/src/test/java/org/dspace/builder/ItemBuilder.java
  dspace-api/src/test/java/org/dspace/ctask/general/CreateMissingIdentifiersIT.java
  dspace-api/src/test/java/org/dspace/orcid/OrcidQueueConsumerIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ExternalSourcesRestControllerIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/ExternalSourceMatcher.java
Labels: bug, testing framework

#8568 Add Contributing docs to GitHub
  CONTRIBUTING.md
  README.md
Labels: 1 APPROVAL, documentation

#8602 Minor fixes to sync CONTRIBUTING with PR template
  .github/pull_request_template.md
  CONTRIBUTING.md
Labels: 1 APPROVAL

#8548 Update to use GitHub CodeQL for code scanning
  .github/workflows/codescan.yml
Labels: code task

#8402 Updates the canvas dimension method to use multiple bundles.
  dspace-api/src/main/java/org/dspace/iiif/IIIFApiQueryServiceImpl.java
  dspace-api/src/test/data/dspaceFolder/config/spring/api/iiif-processing.xml
  dspace-api/src/test/java/org/dspace/iiif/MockIIIFApiQueryServiceImpl.java
  dspace-iiif/src/main/java/org/dspace/app/iiif/service/CanvasService.java
  dspace-iiif/src/main/java/org/dspace/app/iiif/service/ManifestService.java
  dspace-iiif/src/main/java/org/dspace/app/iiif/service/utils/IIIFUtils.java
  dspace-server-webapp/src/test/data/dspaceFolder/config/spring/api/iiif-processing.xml
  dspace-server-webapp/src/test/java/org/dspace/app/rest/iiif/IIIFControllerIT.java
  dspace-server-webapp/src/test/java/org/dspace/iiif/MockIIIFApiQueryServiceImpl.java
Labels: bug, 1 APPROVAL, integration: IIIF

#8522 Item/Collection admin can't create new version item
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/VersionRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/VersionRestRepositoryIT.java
Labels: bug, component: versioning, 1 APPROVAL

#8565 Common Extendend Regex Parser
  dspace-api/src/main/java/org/dspace/app/util/DCInput.java
  dspace-api/src/main/java/org/dspace/app/util/RegexPatternUtils.java
  dspace-api/src/test/java/org/dspace/app/util/RegexPatternUtilsTest.java
Labels: bug, component: submission

#8591 #8412 In Submission Form, list collections alphabetically
  dspace-api/src/main/java/org/dspace/authorize/AuthorizeServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/service/CollectionService.java
Labels: bug, component: submission, 1 APPROVAL

#8562 Option to skip bitstreams on import, like 'export -x'
  dspace-api/src/main/java/org/dspace/app/itemimport/ItemImport.java
  dspace-api/src/main/java/org/dspace/app/itemimport/ItemImportCLIScriptConfiguration.java
  dspace-api/src/main/java/org/dspace/app/itemimport/ItemImportScriptConfiguration.java
  dspace-api/src/main/java/org/dspace/app/itemimport/ItemImportServiceImpl.java
  dspace-api/src/main/java/org/dspace/app/itemimport/service/ItemImportService.java
Labels: new feature, interface: command-line, tools: import, 1 APPROVAL

#8612 Fix Browse by Title cannot filter by multiple words
  dspace-api/src/main/java/org/dspace/browse/SolrBrowseDAO.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/BrowsesResourceControllerIT.java
Labels: bug, component: Discovery, 1 APPROVAL, usability

#8605 Huge performance improvement on metadata import
  dspace-api/src/main/java/org/dspace/app/bulkedit/MetadataImport.java
  dspace-api/src/main/java/org/dspace/handle/HandleServiceImpl.java
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/h2/V7.5_2022.12.06__index_action_resource_policy.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.5_2022.12.06__index_action_resource_policy.sql
  dspace/config/modules/bulkedit.cfg
Labels: high priority, tools: batch-editing, component: Discovery, tools: import, api
