Repository DSpace/DSpace, pull requests merged in 2022-07, with the labels that each got.

#8391 Enhance comments for dspace.server.url and dspace.ui.url to clarify usage
  dspace/config/dspace.cfg
  dspace/config/local.cfg.EXAMPLE
Labels: bug, configuration, 1 APPROVAL

#8361 Replace new operator with autowire
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/DiscoverFacetsConverter.java
Labels: bug, 1 APPROVAL

#8366 92174: Refactor OpenUrlServiceImplTest to avoid making http requests
  dspace-api/src/main/java/org/dspace/statistics/export/service/OpenUrlServiceImpl.java
  dspace-api/src/test/java/org/dspace/statistics/export/service/OpenUrlServiceImplTest.java
Labels: bug, high priority, 1 APPROVAL

#8411 Final Prepartions/Updates for 6.4 bug-fix-only release
  LICENSE
  LICENSES_THIRD_PARTY
  NOTICE
  README.md
  dspace-api/src/main/resources/Messages.properties
  dspace-xmlui-mirage2/src/main/webapp/xsl/core/page-structure.xsl
  dspace-xmlui/src/main/webapp/themes/Mirage/lib/xsl/core/page-structure.xsl
  dspace/config/dspace.cfg
  dspace/etc/oracle/README.md
  dspace/etc/postgres/README.md
  pom.xml
  src/main/license/third-party-file-groupByLicense.ftl
Labels: code task

#8430 Minor Docker fixes for 6.x. Ensure correct permissions and ensure wget installed
  Dockerfile.cli.jdk8
  Dockerfile.dependencies
  Dockerfile.jdk8
  Dockerfile.jdk8-test
Labels: bug, backend: Docker

#8383 OAI Import errors when indexing without -c option
  dspace-oai/src/main/java/org/dspace/xoai/app/XOAI.java
Labels: bug, interface: OAI-PMH

#2469 [DS-4300] Optionally apply given Handles when importing community/collection structure
  dspace-api/src/main/java/org/dspace/administer/StructBuilder.java
  dspace-api/src/test/java/org/dspace/administer/StructBuilderIT.java
Labels: improvement, interface: command-line, identifier: Handles, tools: import

#8433 maven build speed
  pom.xml
Labels: improvement, code task, 1 APPROVAL

#8421 Ensure Local Filter services are autowired
  dspace-api/src/main/java/org/dspace/content/logic/condition/AbstractCondition.java
  dspace-api/src/test/java/org/dspace/content/logic/LogicalFilterTest.java
Labels: bug, quick win, high priority, 1 APPROVAL, api
