Repository DSpace/DSpace, pull requests merged in 2023-02, with the labels that each got.

#8589 Browse links and "by regex" links in item display (REST)
  dspace-api/src/main/java/org/dspace/browse/CrossLinks.java
  dspace-api/src/test/data/dspaceFolder/config/local.cfg
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/BrowseIndexRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/BrowsesResourceControllerIT.java
  dspace/config/dspace.cfg
Labels: improvement, interface: REST API v7

#8653 Fix for "All of DSpace" browse menu has odd behavior for Community/Collection Admins
  dspace-api/src/main/java/org/dspace/browse/SolrBrowseDAO.java
Labels: bug, 1 APPROVAL

#8619 Self register domains restriction
  dspace-api/src/main/java/org/dspace/eperson/AccountServiceImpl.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RegistrationRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/EPersonRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RegistrationRestRepositoryIT.java
  dspace/config/modules/authentication-password.cfg
  dspace/config/modules/rest.cfg
Labels: bug, high priority, authentication: password, authentication: EPerson, 1 APPROVAL, authentication: general

#8628 Downloading restricted bitstreams does not work when opening a new tab/window
  dspace-server-webapp/src/main/java/org/dspace/app/rest/AuthenticationRestController.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/AuthenticationRestControllerIT.java
Labels: bug, high priority, authorization, 1 APPROVAL

#8624 System-wide alerts
  dspace-api/src/main/java/org/dspace/alerts/AllowSessionsEnum.java
  dspace-api/src/main/java/org/dspace/alerts/SystemWideAlert.java
  dspace-api/src/main/java/org/dspace/alerts/SystemWideAlertServiceImpl.java
  dspace-api/src/main/java/org/dspace/alerts/dao/SystemWideAlertDAO.java
  dspace-api/src/main/java/org/dspace/alerts/dao/impl/SystemWideAlertDAOImpl.java
  dspace-api/src/main/java/org/dspace/alerts/service/SystemWideAlertService.java
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/h2/V7.5_2022.12.15__system_wide_alerts.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/oracle/V7.5_2022.12.15__system_wide_alerts.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.5_2022.12.15__system_wide_alerts.sql
  dspace-api/src/test/java/org/dspace/alerts/SystemWideAlertServiceTest.java
  dspace-api/src/test/java/org/dspace/builder/AbstractBuilder.java
  dspace-api/src/test/java/org/dspace/builder/SystemWideAlertBuilder.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/SystemWideAlertConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/SystemWideAlertRest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/hateoas/SystemWideAlertResource.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/SystemWideAlertRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/SystemWideAlertRestRepositoryIT.java
  dspace/config/hibernate.cfg.xml
  dspace/config/spring/api/core-dao-services.xml
  dspace/config/spring/api/core-services.xml
Labels: new feature

#8664 Bitstream command line cleanup operation - huge running time and potentially missing a DB commit
  dspace-api/src/main/java/org/dspace/storage/bitstore/BitstreamStorageServiceImpl.java
Labels: bug, 1 APPROVAL

#8629 Advanced workflow - framework, workflows scoreReview and selectSingleReviewer
  dspace-api/src/main/java/org/dspace/workflow/WorkflowService.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/Role.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/XmlWorkflowServiceImpl.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/Action.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/ActionAdvancedInfo.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/WorkflowActionConfig.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/AcceptEditRejectAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/FinalEditAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/ProcessingAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/ReviewAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/ScoreEvaluationAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/ScoreReviewAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/ScoreReviewActionAdvancedInfo.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/SelectReviewerAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/SelectReviewerActionAdvancedInfo.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/processingaction/SingleUserReviewAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/userassignment/AutoAssignAction.java
  dspace-api/src/main/java/org/dspace/xmlworkflow/state/actions/userassignment/ClaimAction.java
  dspace-api/src/test/data/dspaceFolder/config/spring/api/workflow-actions.xml
  dspace-api/src/test/data/dspaceFolder/config/spring/api/workflow.xml
  dspace-api/src/test/java/org/dspace/xmlworkflow/XmlWorkflowServiceIT.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/ScoreReviewActionAdvancedInfoConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/SelectReviewerActionAdvancedInfoConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/WorkflowActionConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/AdvancedInfoRest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/ScoreReviewActionAdvancedInfoRest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/SelectReviewerActionAdvancedInfoRest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/WorkflowActionRest.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/TaskRestRepositoriesIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/WorkflowActionRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/WorkflowActionMatcher.java
  dspace/config/modules/workflow.cfg
  dspace/config/registries/workflow-types.xml
  dspace/config/spring/api/workflow-actions.xml
  dspace/config/spring/api/workflow.xml
Labels: component: workflow

#8620 Subscription feature rest
  dspace-api/src/main/java/org/dspace/content/CollectionServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/CommunityServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/crosswalk/SubscriptionDsoMetadataForEmailCompose.java
  dspace-api/src/main/java/org/dspace/content/factory/ContentServiceFactory.java
  dspace-api/src/main/java/org/dspace/content/factory/ContentServiceFactoryImpl.java
  dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryConfigurationService.java
  dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoveryRelatedItemConfiguration.java
  dspace-api/src/main/java/org/dspace/discovery/configuration/DiscoverySortFunctionConfiguration.java
  dspace-api/src/main/java/org/dspace/eperson/FrequencyType.java
  dspace-api/src/main/java/org/dspace/eperson/SubscribeCLITool.java
  dspace-api/src/main/java/org/dspace/eperson/SubscribeServiceImpl.java
  dspace-api/src/main/java/org/dspace/eperson/Subscription.java
  dspace-api/src/main/java/org/dspace/eperson/SubscriptionParameter.java
  dspace-api/src/main/java/org/dspace/eperson/dao/SubscriptionDAO.java
  dspace-api/src/main/java/org/dspace/eperson/dao/SubscriptionParameterDAO.java
  dspace-api/src/main/java/org/dspace/eperson/dao/impl/SubscriptionDAOImpl.java
  dspace-api/src/main/java/org/dspace/eperson/dao/impl/SubscriptionParameterDAOImpl.java
  dspace-api/src/main/java/org/dspace/eperson/service/SubscribeService.java
  dspace-api/src/main/java/org/dspace/subscriptions/ContentGenerator.java
  dspace-api/src/main/java/org/dspace/subscriptions/SubscriptionEmailNotification.java
  dspace-api/src/main/java/org/dspace/subscriptions/SubscriptionEmailNotificationCli.java
  dspace-api/src/main/java/org/dspace/subscriptions/SubscriptionEmailNotificationCliScriptConfiguration.java
  dspace-api/src/main/java/org/dspace/subscriptions/SubscriptionEmailNotificationConfiguration.java
  dspace-api/src/main/java/org/dspace/subscriptions/SubscriptionEmailNotificationService.java
  dspace-api/src/main/java/org/dspace/subscriptions/SubscriptionEmailNotificationServiceImpl.java
  dspace-api/src/main/java/org/dspace/subscriptions/objectupdates/CollectionUpdates.java
  dspace-api/src/main/java/org/dspace/subscriptions/objectupdates/CommunityUpdates.java
  dspace-api/src/main/java/org/dspace/subscriptions/service/DSpaceObjectUpdates.java
  dspace-api/src/main/java/org/dspace/subscriptions/service/SubscriptionGenerator.java
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/h2/V7.5_2022.12.01__add_table_subscriptionparamter_change_columns_subscription_table.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/oracle/V7.5_2022.12.01__add_table_subscriptionparamter_change_columns_subscription_table.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.5_2022.12.01__add_table_subscriptionparamter_change_columns_subscription_table.sql
  dspace-api/src/test/data/dspaceFolder/config/local.cfg
  dspace-api/src/test/java/org/dspace/builder/AbstractBuilder.java
  dspace-api/src/test/java/org/dspace/builder/SubscribeBuilder.java
  dspace-api/src/test/java/org/dspace/eperson/SubscribeServiceIT.java
  dspace-api/src/test/java/org/dspace/matcher/SubscribeMatcher.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/authorization/impl/CanSubscribeFeature.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/SubscriptionConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/SubscriptionParameterRest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/SubscriptionRest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/hateoas/SubscriptionResource.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/SubscriptionDSpaceObjectLinkRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/SubscriptionEPersonLinkRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/SubscriptionRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/SubscriptionRestPermissionEvaluatorPlugin.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/SubscriptionRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/authorization/CanSubscribeFeatureIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/SubscriptionMatcher.java
  dspace/config/emails/subscription
  dspace/config/emails/subscriptions_content
  dspace/config/hibernate.cfg.xml
  dspace/config/launcher.xml
  dspace/config/spring/api/core-dao-services.xml
  dspace/config/spring/api/scripts.xml
  dspace/config/spring/api/subscriptions_email_configuration.xml
Labels: new feature, 1 APPROVAL

#8663 [DURACOM-116] process sorted alphabetically
  dspace-api/src/main/java/org/dspace/scripts/ScriptServiceImpl.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/ScriptRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ScriptRestRepositoryIT.java
Labels: bug, 1 APPROVAL

#8621 Supervision order REST endpoints
  dspace-api/src/main/java/org/dspace/content/InstallItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/SupervisedItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/WorkspaceItem.java
  dspace-api/src/main/java/org/dspace/content/WorkspaceItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/content/dao/WorkspaceItemDAO.java
  dspace-api/src/main/java/org/dspace/content/dao/impl/WorkspaceItemDAOImpl.java
  dspace-api/src/main/java/org/dspace/content/factory/ContentServiceFactory.java
  dspace-api/src/main/java/org/dspace/content/factory/ContentServiceFactoryImpl.java
  dspace-api/src/main/java/org/dspace/content/service/SupervisedItemService.java
  dspace-api/src/main/java/org/dspace/content/service/WorkspaceItemService.java
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceSupervisionOrderIndexingPlugin.java
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceWorkspaceWorkflowRestrictionPlugin.java
  dspace-api/src/main/java/org/dspace/discovery/indexobject/InprogressSubmissionIndexFactoryImpl.java
  dspace-api/src/main/java/org/dspace/eperson/Group.java
  dspace-api/src/main/java/org/dspace/eperson/GroupServiceImpl.java
  dspace-api/src/main/java/org/dspace/eperson/SupervisorServiceImpl.java
  dspace-api/src/main/java/org/dspace/eperson/factory/EPersonServiceFactory.java
  dspace-api/src/main/java/org/dspace/eperson/factory/EPersonServiceFactoryImpl.java
  dspace-api/src/main/java/org/dspace/eperson/service/SupervisorService.java
  dspace-api/src/main/java/org/dspace/supervision/SupervisionOrder.java
  dspace-api/src/main/java/org/dspace/supervision/SupervisionOrderServiceImpl.java
  dspace-api/src/main/java/org/dspace/supervision/dao/SupervisionOrderDao.java
  dspace-api/src/main/java/org/dspace/supervision/dao/impl/SupervisionOrderDaoImpl.java
  dspace-api/src/main/java/org/dspace/supervision/enumeration/SupervisionOrderType.java
  dspace-api/src/main/java/org/dspace/supervision/factory/SupervisionOrderServiceFactory.java
  dspace-api/src/main/java/org/dspace/supervision/factory/SupervisionOrderServiceFactoryImpl.java
  dspace-api/src/main/java/org/dspace/supervision/service/SupervisionOrderService.java
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/h2/V7.5_2022.12.09__Supervision_Orders_table.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/oracle/V7.5_2022.12.09__Supervision_Orders_table.sql
  dspace-api/src/main/resources/org/dspace/storage/rdbms/sqlmigration/postgres/V7.5_2022.12.09__Supervision_Orders_table.sql
  dspace-api/src/test/java/org/dspace/builder/AbstractBuilder.java
  dspace-api/src/test/java/org/dspace/builder/SupervisionOrderBuilder.java
  dspace-api/src/test/java/org/dspace/content/SupervisedItemTest.java
  dspace-api/src/test/java/org/dspace/supervision/SupervisionOrderServiceIT.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/converter/SupervisionOrderConverter.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/SupervisionOrderRest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/WorkspaceItemRest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/model/hateoas/SupervisionOrderResource.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/SupervisionOrderRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/WorkspaceItemSupervisionOrdersLinkRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WorkflowRestPermissionEvaluatorPlugin.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/security/WorkspaceItemRestPermissionEvaluatorPlugin.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/Utils.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/SupervisionOrderRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/WorkflowItemRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/WorkspaceItemRestRepositoryIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/FacetEntryMatcher.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/FacetValueMatcher.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/SupervisionOrderMatcher.java
  dspace/config/hibernate.cfg.xml
  dspace/config/spring/api/core-dao-services.xml
  dspace/config/spring/api/core-factory-services.xml
  dspace/config/spring/api/core-services.xml
  dspace/config/spring/api/discovery.xml
Labels: new feature, 1 APPROVAL

#8660 Fix for Delete items after copies have been requested
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemServiceImpl.java
  dspace-api/src/main/java/org/dspace/app/requestitem/dao/RequestItemDAO.java
  dspace-api/src/main/java/org/dspace/app/requestitem/dao/impl/RequestItemDAOImpl.java
  dspace-api/src/main/java/org/dspace/app/requestitem/service/RequestItemService.java
  dspace-api/src/main/java/org/dspace/content/ItemServiceImpl.java
  dspace-api/src/test/java/org/dspace/content/service/ItemServiceTest.java
Labels: bug, 1 APPROVAL

#8665 Downgrade Creative Commons transformation stylesheet version
  dspace-api/src/main/resources/org/dspace/license/CreativeCommons.xsl
  dspace-api/src/main/resources/org/dspace/license/LicenseCleanup.xsl
Labels: bug, interface: OAI-PMH, 1 APPROVAL
