Repository DSpace/DSpace, pull requests merged in 2023-01, with the labels that each got.

#8611 Add "./dspace database skip" command to optionally skip older migrations
  dspace-api/src/main/java/org/dspace/storage/rdbms/DatabaseUtils.java
Labels: bug, high priority, interface: command-line, backend: FlywayDB, 1 APPROVAL

#8593 DataCite plugin for import
  dspace-api/src/main/java/org/dspace/importer/external/datacite/DataCiteFieldMapping.java
  dspace-api/src/main/java/org/dspace/importer/external/datacite/DataCiteImportMetadataSourceServiceImpl.java
  dspace-api/src/main/resources/spring/spring-dspace-addon-import-services.xml
  dspace-api/src/test/data/dspaceFolder/config/spring/api/external-services.xml
  dspace-server-webapp/src/test/java/org/dspace/app/rest/DataCiteImportMetadataSourceServiceIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/ExternalSourcesRestControllerIT.java
  dspace-server-webapp/src/test/resources/org/dspace/app/rest/dataCite-test.json
  dspace/config/modules/external-providers.cfg
  dspace/config/spring/api/datacite-integration.xml
  dspace/config/spring/api/external-services.xml
Labels: new feature, 1 APPROVAL, tools: import-sources

#8626 Configuration updated to highlight Orgunit and Person
  dspace/config/spring/api/discovery.xml
Labels: bug, component: Discovery, 1 APPROVAL

#8631 [DURACOM-113] add jfif extension on bitstream formats
  dspace/config/registries/bitstream-formats.xml
Labels: configuration, 1 APPROVAL

#8625 Add CORS "Access-Control-Expose-Headers: Accept-Ranges" header
  dspace-server-webapp/src/main/java/org/dspace/app/rest/utils/HttpHeadersInitializer.java
Labels: bug, 1 APPROVAL

#8319 Enable to answer a request a copy using "helpdesk" strategy
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemAuthorExtractor.java
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemEmailNotifier.java
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemHelpdeskStrategy.java
  dspace-api/src/main/java/org/dspace/app/requestitem/RequestItemSubmitterStrategy.java
  dspace-api/src/test/java/org/dspace/app/requestitem/RequestItemHelpdeskStrategyTest.java
  dspace-api/src/test/java/org/dspace/app/requestitem/RequestItemSubmitterStrategyTest.java
  dspace-server-webapp/pom.xml
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/RequestItemRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/RequestItemRepositoryIT.java
  dspace/config/spring/api/requestitem.xml
Labels: bug, high priority, authorization

#8600 Issue 815 controlled vocabulary hierarchical facets 7.4
  dspace-api/src/main/java/org/dspace/content/authority/DSpaceControlledVocabulary.java
  dspace-api/src/test/java/org/dspace/content/authority/DSpaceControlledVocabularyTest.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/VocabularyEntryDetailsChildrenLinkRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/VocabularyEntryDetailsParentLinkRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/VocabularyEntryDetailsRestRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/VocabularyEntryLinkRepository.java
  dspace-server-webapp/src/main/java/org/dspace/app/rest/repository/VocabularyRestRepository.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/EPersonAuthorityIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/VocabularyEntryDetailsIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/VocabularyRestRepositoryIT.java
Labels: component: Discovery, 1 APPROVAL, component: controlled vocabulary

#8613 Facet search should search all words, not just the first one
  dspace-api/src/main/java/org/dspace/discovery/DiscoverResult.java
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceImpl.java
  dspace-api/src/main/java/org/dspace/discovery/SolrServiceMetadataBrowseIndexingPlugin.java
  dspace-api/src/main/java/org/dspace/discovery/indexobject/ItemIndexFactoryImpl.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/DiscoveryRestControllerIT.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/matcher/FacetValueMatcher.java
  dspace/solr/search/conf/schema.xml
Labels: bug, high priority, component: Discovery, e/12, usability, claimed: Atmire

#8578 Update Apache Commons BCEL and add "test" scope
  dspace-api/pom.xml
Labels: bug, high priority, dependencies, 1 APPROVAL

#8642 Use discovery configurations in browse
  dspace-api/src/main/java/org/dspace/browse/BrowseDAO.java
  dspace-api/src/main/java/org/dspace/browse/BrowseEngine.java
  dspace-api/src/main/java/org/dspace/browse/SolrBrowseDAO.java
  dspace-server-webapp/src/test/java/org/dspace/app/rest/BrowsesResourceControllerIT.java
Labels: bug, authorization, component: Discovery, e/8
