Repository DSpace/DSpace, pull requests merged in 2024-10, with the labels that each got.

#9777 several optimizations in HAL browser login page
  dspace-server-webapp/src/main/resources/static/login.html
Labels: bug, interface: REST API v7+, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#9885 Bump to Spring 6.1.13, Spring Boot 3.3.4 and Spring Security 6.3.3
  dspace-server-webapp/pom.xml
  pom.xml
Labels: dependencies, port to dspace-8_x

#9888 Bump `dspace-7_x` to Spring 5.3.39 and Spring Security 5.7.12
  dspace-server-webapp/pom.xml
  pom.xml
Labels: dependencies

#9894 Add Eclipse JDT .factorypath to .gitignore
  .gitignore
Labels: quick win, 1 APPROVAL, port to dspace-7_x, port to dspace-8_x

#9926 Create `dependabot.yml` to auto-update Maven dependencies (`main` only)
  .github/dependabot.yml
Labels: dependencies, 1 APPROVAL
